### ISSUE TITLE
ReSharper doesn't show any output for xunit.net tests

### ISSUE THREAD

**Issue by Tuomask** [xunit/resharper-xunit#100]
When I run tests in my project, it doesn't give any output for the failing tests.
The output window on the ReSharp test runner is just empty.

**Comment by DmitryShadrin** [comment]
+1

**Comment by trbngr** [comment]
came here to report this as well.

**Comment by citizenmatt** [comment]
This is a bug in ReSharper itself ([RSRP-450266](https://youtrack.jetbrains.com/issue/RSRP-450266)). It's been fixed and will be released very soon, in a matter of days. I'll leave this ticket open until it's available, so others can find it.

**Comment by Tuomask** [comment]
Resharper has been updated, it seems to be fixed.
