### ISSUE TITLE
log4net console output not shown in output window

### ISSUE THREAD

**Issue by JorritSalverda** [xunit/resharper-xunit#102]
I'd like to be able to see the output from the log4net ConsoleAppender in the resharper test output window when running tests, but the output screen remains blank. I read at https://devnet.jetbrains.com/thread/274354 that it's the responsibility of the plugin to support that.

**Comment by citizenmatt** [comment]
If you're using xunit 2, then the output won't get captured, due to running tests concurrently - you can't tell which test a piece of output belongs to. See [the docs for more details](http://xunit.github.io/docs/capturing-output.html).

**Comment by citizenmatt** [comment]
Closing this. If there are any more questions, please reopen, or log a new issue.

**Comment by drauch** [comment]
Summed up, there is no way to capture output from the SUT (which of course cannot use `ITestOutputHelper`)?

This is a rather heavy restriction ... is there a way to set xunit to "serialized mode" and capture output that way?

This would REALLY help debugging, e.g. I'm currently developing graph algorithms, where nice output can show problems very fast while using the debugger UI leads to massive amount of breakpoint hits...

**Comment by citizenmatt** [comment]
No, there's no way of doing this. It might be worth suggesting something on the main xunit repo.

**Comment by drauch** [comment]
In case someone else also stumbles into this thread: https://github.com/xunit/xunit/issues/1038
