### ISSUE TITLE
Methods in abstract class identified as tests when a test is in the class

### ISSUE THREAD

**Issue by elderfo** [xunit/resharper-xunit#105]
All of my test classes inherit a base class which has common methods, etc... When doing unit tests with mocked objects, I have a default test in the base class that is used to validate that all mocks have been instantiated and the object I am testing can be created. Due to this, I noticed that the methods from the base class show up as tests in the VS/R# test explorer. 

Here is a simple example:
```
public class MyTests : TestClass
{
	[Fact]
	public void FailingTest()
	{
		Assert.Equal(6, Subtract(8, 1));
	}

	[Fact]
	public void PassingTest()
	{
		Assert.Equal(3, Add(1, 2));
	}
}

public abstract class TestClass
{
	[Fact]
	public void BaseClassTest()
	{
		Assert.Equal(2, Add(1,1));
	}

	public int Subtract(int first, int second)
	{
		return first - second;
	}

	protected int Add(int first, int second)
	{
		return first + second;
	}

	private int Multiply(int first, int second)
	{
		return first * second;
	}
}
```
In this example I should see 3 tests, (PassingTest, FailingTest and BaseClassTest). Instead, I see the expected ones plus Add, Subtract and Multiply.

**Comment by citizenmatt** [comment]
It's harmless, they're just test elements that will never be run. But it's fixed, please get the latest version (2.3.3) from the extension manager.

**Comment by elderfo** [comment]
Thank you, I am glad they won't be there anymore. :+1:

**Comment by georgiosd** [comment]
Has this behavior been changed? I'm trying to share some tests between two classes like:

`abstract class TestsBase { /* Facts */ }`
`class ATests : TestsBase { }`
`class BTests : TestsBase { }`

and I get:

```
2017.05.17 22:59:12.447   ERROR System.InvalidOperationException: Test from abstract fixture is not runnable itself
   at JetBrains.ReSharper.UnitTestProvider.Xunit.UnitTestElements.XunitInheritedTestMethodContainerElement.GetTaskSequence(ICollection`1 explicitElements, IUnitTestRun run)
   at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestRun.AddElement(IUnitTestElement element, ICollection`1 explicitElements)
   at JetBrains.ReSharper.UnitTestFramework.Launch.Stages.BuildPipelineStage.DistributeElementsIntoRunsStage.<>c__DisplayClass14.<Run>b__d()
   at JetBrains.ReSharper.UnitTestFramework.Launch.UnitTestLaunchLogMessageExtensions.Catch(IUnitTestLaunchOutput output, Action action, LoggingLevel level)
```

Note that VS2017 runs the tests fine...
