### ISSUE TITLE
Test runner creates two different sets of test instances on subsequent runs (using Theory with PropertyDataAttribute)

### ISSUE THREAD

**Issue by jongleur1983** [xunit/resharper-xunit#106]
Hi,
I have a problem with the Resharper Testrunner for XUnit on the following test Theory:

```[Theory]
[PropertyData("InputCriteria")]
public void BottleneckValidFilterActionTest(
    string id,
    NA2000CriterionVersion inputCriterion, 
    bool filterOnBegin, 
    DateTime? filterRangeStartsAfter, 
    DateTime? filterRangeStartsBefore, 
    Scenario scenario,
    bool shouldBeReturned)
{
    var action = new BottleneckValidFilterAction(new GetBottlenecks());
    var result = action.Apply(
        new [] { new CriterionWrapperMock(inputCriterion) }.AsEnumerable(), 
        filterOnBegin, 
        filterRangeStartsAfter, 
        filterRangeStartsBefore, 
        scenario);
    Assert.Equal(shouldBeReturned, result.Any());
}
```

The Property "InputCriteria" returns 32 instances for this test, four of those failing.
Running the test results in one of two screens:

On the first screen, only 6 test instances are shown, four of them failed, two succeeded (the result is as expected). The bar above the test instance tree reflects these numbers, the Test that should have 26 instances shows "(26 tests)", but lists only the six.
![xunittestrunnershot1](https://cloud.githubusercontent.com/assets/2063360/11785617/f4d9594e-a282-11e5-96cd-7bbb7fa7d389.png)

The second screen shows 26 succeeding instances, where all have passed, but shows the test itself as "some tests failed" (the red icon).

![xunittestrunnershot2](https://cloud.githubusercontent.com/assets/2063360/11785618/f4dcef14-a282-11e5-912a-ff52a38971fb.png)

Looking carefully, I observed that while running the test, the list seems to be complete. For the first case it lists many "succeeded" tests, while for the second it lists's some failed onces.
In both cases the list loses some instances when finishing.

Cross-checking with the Visual studio test runner results in the correct (but ugly looking and hardly usable) behaviour: it lists 32 test instances in it's log, four failing, 28 succeeding.

As far as I can tell, subsequent runs alternate the two cases, but I'm not sure if that assumption is really valid.

The PropertyData property always returns the same objects, it is used only to built some more complex data structures.

**Comment by citizenmatt** [comment]
This is a bug in ReSharper, annoyingly. The test runner has to dynamically add these theory tests, and the ReSharper bug immediately deletes them once the test run has completed. Here's the bug: [RSRP-451046](https://youtrack.jetbrains.com/issue/RSRP-451046). I'll close this, as it should be fixed with ReSharper 10.0.2.

**Comment by citizenmatt** [comment]
Actually, I've just tested with EAP5, and it's all working again. Theories appear to be run properly again.

**Comment by jongleur1983** [comment]
great, thanks for the immediate response, will test it once 10.0.2 is there.

**Comment by jongleur1983** [comment]
Works with Resharper 10.0.2 EAP 5, which is available at https://confluence.jetbrains.com/display/ReSharper/ReSharper+10.0.2+EAP
