### ISSUE TITLE
Update to 10.0.2, xUnit no longer showing in the Extensions gallery or working with dotCover

### ISSUE THREAD

**Issue by mikeschuld** [xunit/resharper-xunit#107]
I just installed the 10.0.2 update for ReSharper Ultimate. None of my xUnit tests are running through dotCover now.

I tried to uninstall/reinstall the extension, but it no longer shows in the gallery.

**Comment by citizenmatt** [comment]
That's odd, and not what I'm seeing. What do you see in the gallery? Can you let me know what your package sources are? (ReSharper &rarr; Options &rarr; Extension Manager).

**Comment by LarryFix** [comment]
I am seeing similar behavior. My tests are running but dotCover does not think there are any covering tests when I right click on a class node in the coverage tree. 

The package information on the Extension Manager window is https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v4.0/

**Comment by mikeschuld** [comment]
Same URL for me: [https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v4.0/](https://resharper-plugins.jetbrains.com/api/v2/curated-feeds/Wave_v4.0/)

Tests still seem to be getting discovered by Visual Studio, but were not showing in dotCover.

Note: I do not have the xUnit runner installed as it was working without it before.

**Comment by citizenmatt** [comment]
Oops. Got it wrong in my first reply. Tests are running normally, but they are NOT getting covered. Fully reproduced, something's changed in 10.0.2. Here's the bug: [DCVR-7976](https://youtrack.jetbrains.com/issue/DCVR-7976).

Secondly, I'm not sure what's going on with the feed. That URL is correct, and I'm seeing xunit in the results. Is the whole list empty? If so, can you check you only have one ".NET Products Gallery" item in the Extension Manager source list - having more than one can cause an issue.

**Comment by LarryFix** [comment]
I only have the one item in the source list that citezenmatt mentioned.

**Comment by citizenmatt** [comment]
Are you behind a proxy or corporate firewall?

**Comment by mikeschuld** [comment]
The extension list is not empty, it just doesn't contain this project when searching. "TestCop for ReSharper 10" and "InternalsVisibleTo Helper for ReSharper" are the only results that return when searching for xunit

**Comment by citizenmatt** [comment]
It's definitely in the feed.

Are those two extensions already installed? Are you behind a proxy or corporate firewall?

**Comment by mikeschuld** [comment]
They are not installed. When xUnit-Resharper was still installed it still showed in the list, but would not run any coverage or discover those tests in ReSharper (same problem it seems others are having).

I tried to uninstall and reinstall the package, and that is when I created this issue since it no longer showed up in the list of available packages at that point. I am at work, but we don't really have what would be considered a "corporate firewall". This seems to be unrelated to firewall anyway since I just installed the package for the first time only a few days before the 10.0.2 ReSharper upgrade and it stopped working/showing up immediately after that upgrade.

Is there an easy way to just install it from source so I can use it that way until we can figure out what is going on with the missing package?

**Comment by citizenmatt** [comment]
Before you install manually, can you open the extension manager with Fiddler running, please? It'll need to be configured to decrypt https, but you should then be able to see the feeds that are being returned by the server, and we should be able to see the xunit plugin in there.

As for installing manually, you can download from [this page](https://resharper-plugins.jetbrains.com/packages/CitizenMatt.Xunit/), as long as you're logged into the gallery. Once you've got it downloaded, add the download folder to the ReSharper &rarr; Options &rarr; Extension Manager sources list. Reopen the extension manager, and it should be listed in there as available to install.

**Comment by joukevandermaas** [comment]
Note that you can get the coverage if you right click the topmost node, select 'Cover in continuous testing' and start a new continuous testing session. On the cover tab of that view, the coverage results are shown.

**Comment by mikeschuld** [comment]
Got back in to work this morning and the extension is now showing up in the list again. Made no changes on my end other than installing and opening Fiddler, but it is showing in the list with or without Fiddler running. Would love to know what fixed that for me.

I do still have the issue with my project containing the test classes not showing in the Coverage Tree. Though they DO show when I try @joukevandermaas suggestion with Continuous testing. They don't show in the continuous testing list of tests, but they do in the coverage tree in that window.

I do see the projects in the normal unit testing window when clicking a different node in the Unit Test Sessions and running cover on it, but when right clicking the tests that I am actually trying to cover, neither the test project nor the code library it tests are showing in the coverage tree.

Is it possible that the tree is just hiding projects with 100% coverage? I know this specific test project and library have 100% coverage which may explain why it is suddenly hiding.

When you run cover on a node somewhere else in the test tree the coverage for other projects isn't 100% since the specifically run tests don't cover it, so that may be the reason why it shows in that case. They also DO show in the Continuous coverage tree even with 100%.

One final note, there are some non xUnit tests in a different project (MSTest) that are behaving normally.

**Comment by joukevandermaas** [comment]
For what it's worth, it's not that the project has 100% coverage. Mine has ~98 but it still doesn't show. 

I did manage to make one project show up in the coverage tree after clicking around semi-randomly, but not the one I wanted. The continuous testing work-around will do for now until the Resharper team fixes the issue.

**Comment by citizenmatt** [comment]
This looks like it has something to do with shadow copy. If you disable it in the ReSharper &rarr; Unit Testing options, then the code coverage works. If it's enabled, code coverage doesn't work. I don't know yet if this is a ReSharper/dotCover thing, or something I can fix in the plugin.

At least there's a workaround for now.

**Comment by mikeschuld** [comment]
That seems to have solved this issue for me.

**Comment by LarryFix** [comment]
Disabling the shadow copying cleared up the problem for me too. Thanks for the workaround.

**Comment by citizenmatt** [comment]
This is fixed as part of the ReSharper 10.1 support - the workaround won't be necessary any longer.
