### ISSUE TITLE
xUnit runner doesn't work with .net 4.6.1

### ISSUE THREAD

**Issue by Ermesx** [xunit/resharper-xunit#108]
Hi,
When I create my project I set .net target framework to 4.6.1 then I wrote some code and created some tests but when I try to run tests occur error like below:
![2015-12-24 18_47_34-ae core - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/5731890/11997770/f5ddcdc4-aa85-11e5-8ffc-1b6c9ea715ff.png)
Sorry for polish description on the screen :)

I checked all dependencies but all are correct.
The issue disappeared when I change target framework to .net 4.5.2.

For now I will use .net 4.5.2.
Could you help me ?

I use Visual Studio 2013 with all updates and Resharper 8.2.3

**Comment by citizenmatt** [comment]
A `BadImageFormatException` means you're trying to load an assembly that has a different "bit-ness" to the host process. In other words, I suspect the assembly containing production code is set to 32 bit, while the test assembly is 64 bit or AnyCPU (or vice versa). Make sure both assembly projects have the same bit-ness and it should work fine.

**Comment by citizenmatt** [comment]
Has this fixed the issue? I'm closing this for now - please reopen if it's not sorted.
