### ISSUE TITLE
Console.Out not displayed in output panel

### ISSUE THREAD

**Issue by drewnoakes** [xunit/resharper-xunit#109]
If a test writes to `Console.Out` (or `Debug.Write`) then that output does not appear in the output pane of the test runner.

VS2015
R# Ultimate 10.0.2
resharper-xunit 2.3.2

**Comment by bradwilson** [comment]
You don't mention the version of xUnit.net you're using, but I'm assuming it's 2.x. The [release notes for 2.0](http://xunit.github.io/release-notes/2015-03-16.html) mention this:

> Test Output
>
> In xUnit.net v1, we captured output written to standard output, standard error, the debug channel, and the trace channel, and we surfaced this output up to the test runners (which displayed them in a way that was appropriate to the test). In addition, the output was placed into the XML output, if you saved the result of your test runs.
>
> With xUnit.net v2, we have stopped capturing these sources. The primary reason is that these are shared resources, and it's impossible to know which of the many unit tests running in parallel might be writing to the console or the tracing system. Instead, tests can accept `ITestOutputHelper` as a constructor argument, and use that to provide output that is reported up to the runners (and placed into the XML results). It can be used from the constructor, from within the test, and from within `IDisposable.Dispose()` (if it's defined).
>
> For more information on using test output, please see the [TestOutputExample](https://github.com/xunit/samples.xunit/blob/master/TestOutputExample) sample project.

**Comment by citizenmatt** [comment]
What Brad said :) If you're not using xunit2, then please reopen.

**Comment by drewnoakes** [comment]
Apologies for my slow response. Christmas time.

I'm using 2.1.0. Using `ITestOutputHelper` works, thanks. I understand the problem it's trying to solve, and it's an elegant solution to that problem. Would be great if it could be more discoverable. Perhaps the test runner could notice anything appearing on stdout/stderr and suggest using this technique.
