### ISSUE TITLE
Resharper-xUnit totally trashes ReSharper itself when working on DNX code.

### ISSUE THREAD

**Issue by bradykelly** [xunit/resharper-xunit#110]
I have seldom had a more unpleasant day's coding (day and night actually) than when this  extension was installed. It completely disabled _most_ other ReSharper functionality in the very simple xUnit test class I was working on.

My test project was created with the "xUnit Test Project (DNX)" template and targets the "dnx46" platform. It was created to test a DNX46 class library, and I am running the following xUnit packages:
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
The sad thing is, the code that was such hell working with was dead standard C# & xUnit code, with nothing at all DNX specific. Guys, DNX is already in RC1 Update 1. xUnit is currently the only unit test framework compatible with DNX, and if you guys ignore this, you will lose huge market share.

I left it so long before uninstalling because I couldn't believe this extension had interfered so much with ReSharper's normal working.

**Comment by citizenmatt** [comment]
This extension doesn't support DNX tests right now - the entire environment for running tests is different to standard .net framework apps, and requires underlying changes in ReSharper itself. See #38.

I haven't had any reports that the extension breaks "*any* other ReSharper functionality". I appreciate your frustration, but reporting an issue without any exceptions, error messages or other details, while using language like "cursed extension" and "JetBrains are not going to enjoy hearing about this" isn't the best way to ask for help.

**Comment by bradykelly** [comment]
Thanks for your feedback, and I apologize for the strong wording and allusion to threats, and have edited my OP to tone it down a bit. As to error messages and details, nearly all my code had red underlines, things like "go to declaration" etc. weren't working, no auto-complete was working, other R# shortcuts that escape me now weren't working, and the text editor itself seemed to be struggling.

The "good" side is the test still compiled and passed.

**Comment by citizenmatt** [comment]
The red code shouldn't be caused by the test runner extension. Did it go away after removing the xunit extension? And are you on ReSharper 10.0.2? One of the problems with DNX, etc. is that despite it being at RC status, it's very volatile, and still changing, which makes supporting it in ReSharper so much harder. 10.0.2 has just been released, and has the latest set of fixes, so should hopefully work a lot better. The xunit runner still works with this release.

**Comment by bradykelly** [comment]
Yes, funny, I am using 10.0.2, and the red did go away after removing the plugin. Maybe just a peak in the volatility of DNX.
