### ISSUE TITLE
2.3.3 showing diagnostic Errors popup where 9 wasn't, how to disable?

### ISSUE THREAD

**Issue by bluto56** [xunit/resharper-xunit#111]
Hello,

In resharper 9 with the 2.x.x version of the test runner we were getting no pop ups regarding xunit test runer diagnostic messages.

After the upgrade to 10 and 2.3.3 on every test run we receive the attached screen shot.

I guess this isn't a bug, per se. Maybe a debug setting got checked in or some such configuration issue. Can you provide guidance on how to disable this pop up/change this setting?

Thanks,
Matt

![xunit resharper10 runner 2 3 3 diagnositc error](https://cloud.githubusercontent.com/assets/1538695/12629773/38c5530c-c541-11e5-903f-e4e0891585da.png)

**Comment by citizenmatt** [comment]
Diagnostics are enabled if the flag is enabled in the xunit config ([json](http://xunit.github.io/docs/configuring-with-json.html) or [xml](http://xunit.github.io/docs/configuring-with-xml.html)), or if ReSharper is in "internal" mode, that is, you've started Visual Studio with `devenv.exe /ReSharper.Internal`.

Are you seeing the popups automatically? Or do you get a notification bar in the unit test sessions window?

**Comment by bluto56** [comment]
Hi Matt,

Ah ha, Some one had enabled diagnostic messages several months ago in our project file.

The behavior we are seeing is a modal dialog box pop up on each test run. We are not seeing a notification pop up in the VS notification bar. We verified on our machines that with 

`<add key="xunit.diagnosticMessages" value="true" />`

on our resharper 9 we see no modal, but with 10 we do. That might be a thing worth changing?

Either way thanks for the guidance.

-Matt

**Comment by bradwilson** [comment]
In my opinion, it would be better if this information was available in some form other than an automatic modal popup. :smiley:

**Comment by citizenmatt** [comment]
Ugh. Looks like ReSharper's implementation has changed. Test runners have a method that they can use called `ShowNotification`. It used to add a non-intrusive notification bar to the test runner window, which you could click to get a message box with more details. It now just displays a message box. I don't know why it's changed. Ho hum. I'll raise an issue.

In the mean time, though, I think I'm going to leave it as a message box, as there's no other (easy) way to get this information. I'll change the wording a little though, to explain how to disable.

**Comment by citizenmatt** [comment]
Right, here's the issue: [RSRP-453482](https://youtrack.jetbrains.com/issue/RSRP-453482), and I've just pushed a new build that has a bit of extra text telling you how to disable the messages.
