### ISSUE TITLE
Add support for R# 10.1 (EAP / Wave 5.0)

### ISSUE THREAD

**Issue by DoCode** [xunit/resharper-xunit#113]

**Comment by citizenmatt** [comment]
Well, that was quick. The EAP hasn't even been announced yet!

**Comment by DoCode** [comment]
Not a but available and nice to see the new features! :+1: 
https://confluence.jetbrains.com/display/ReSharper/ReSharper+10.1+EAP

I like the supprt for JSON style/code/formatting...
But i miss the integrated xUnit support!!!

**Comment by citizenmatt** [comment]
You might want to stick with 10.0.2 for now, then. Xunit support is going to be at least a week before it's ready...

**Comment by drewnoakes** [comment]
Would also like to see xUnit support for 10.1 EAP. Had to roll back to 10.0 for now.

**Comment by citizenmatt** [comment]
Yep, it's likely going to be EAP3 before you'll have xunit back again. Sorry.

**Comment by drewnoakes** [comment]
@citizenmatt, I don't want to be that guy, but [EAP 3](https://confluence.jetbrains.com/display/ReSharper/ReSharper+10.1+EAP) is out now :)

I've had all sorts of trouble with R# since rolling back to 10.0.

**Comment by codybaxter** [comment]
I have the same question. Wondering when support will be back. Really want to upgrade to the EAP but can't give up xUnit support.

**Comment by citizenmatt** [comment]
Sorry for the delay folks. I am working on it, but I'm afraid you'll have to be patient. To manage your expectations, it's not going to make EAP4, but should be ready for EAP5.

**Comment by drewnoakes** [comment]
Thanks for the update Matt.

Out of interest, is there any chance that this might ship as a default feature of R# in future? Seems xUnit is gaining popularity to the point where people might expect R# to have this out of the box.

**Comment by citizenmatt** [comment]
Do you mean, why haven't I just recompiled the plugin and released it already? :wink:

**Comment by drewnoakes** [comment]
No not at all. How did you get that impression? I honestly don't know what's involved with porting to new versions. I mean, what are the odds that this wouldn't be a plug in and that it would be included as part of R#, just as NUnit support is.

**Comment by citizenmatt** [comment]
(You missed the wink)

**Comment by citizenmatt** [comment]
Let's just see what EAP5 brings :)

**Comment by drewnoakes** [comment]
Well well, sounds exciting :)

**Comment by mdonatas** [comment]
I take it we'll have to wait for EAP6 or later? :)

**Comment by citizenmatt** [comment]
Um. Yes, sorry :(

**Comment by drewnoakes** [comment]
Dang...

Do you know if it's possible to run different configurations of VS with different versions of R# at the same time? I enjoy participating in the EAPs but a break like this has an impact on my workflow. Ideal situation would be to have both available without having to run installers.

**Comment by citizenmatt** [comment]
Yes indeed, in the installer, go to options and select to install into an "experimental instance" or "custom hive" (I can't remember which term the installer uses). This will have a name, such as "Exp" or "ReSharper". This allows you to install multiple versions of ReSharper side-by-side - one in the normal instance, and one in the custom instance. To run, just run `devenv.exe /rootSuffix Exp` (or `/rootSuffix resharper`). But it should only be for another week (fatal last words)...

**Comment by drewnoakes** [comment]
That's great. Thanks very much. I figured at least the R# devs would need
this ability!

This might be useful information to put on the EAP page, if it isn't
already and I just missed it.

**Comment by citizenmatt** [comment]
Y'all might want to give EAP6 a try.

Just sayin'.

:smile:

**Comment by mdonatas** [comment]
Installing! That's sneaky as I haven't seen anything mentioned in issue tracker when it came out :)

**Comment by citizenmatt** [comment]
I don't think it had an issue, to be honest. Blog post tomorrow, or next day.

**Comment by smithkl42** [comment]
I just installed EAP6, but I don't see anything listed in the Resharper Extension Manager for this extension:

![resharperextensions](https://cloud.githubusercontent.com/assets/2381026/13854276/e407837c-ec27-11e5-84d7-034f440f8140.png)

And of course, EAP6 isn't picking up my xunit tests.

Am I just missing something?

**Comment by citizenmatt** [comment]
It's not an extension any more, it's baked into the product now. So it should just recognise the tests. What do you see instead? Also, can you go to the options, and look for Unit Testing -> xunit and see if it's disabled? (It should be enabled by default)

**Comment by smithkl42** [comment]
Odd - I uninstalled it, and reinstalled, and it rediscovered the missing tests. Not sure why it didn't install correctly the first time around. But it's working now.

**Comment by citizenmatt** [comment]
Closing this. Xunit support is [now rolled into the main ReSharper product](http://blog.jetbrains.com/dotnet/2016/03/17/resharper-ultimate-2016-1-formerly-10-1-eap-6/).
