### ISSUE TITLE
Difference in count of available tests

### ISSUE THREAD

**Issue by StuartHemming** [xunit/resharper-xunit#114]
Please have a look at the Flash video referenced below.

It shows a difference in the number of tests available when I create a new Session.

[http://screencast.com/t/KC9WKrCfV](url)

**Comment by citizenmatt** [comment]
Are the missing tests theories?

**Comment by StuartHemming** [comment]
Nope. In the whole suite there is only one Theory. :-(

**Comment by StuartHemming** [comment]
OK. Now this is weird....

**EDIT**
Something wrong with the link. See below.

If I expand the fixture you can see all of the tests even though it says there are only 4!!

**Comment by StuartHemming** [comment]
![2016-02-04_1556](https://cloud.githubusercontent.com/assets/3102909/12820828/a6863c40-cb58-11e5-92db-37270235dba3.png)

**Comment by citizenmatt** [comment]
I believe this is a ReSharper issue rather than the plugin - at least, there has been a bug with a very similar description fixed in the latest 10.1 EAPs. However, xunit isn't ready for EAP yet. It will likely be EAP5.

**Comment by citizenmatt** [comment]
Closing as not reproducible. If there are still problems, please [file an issue with ReSharper](https://youtrack.jetbrains.com) (as the xunit plugin is now a part of ReSharper)
