### ISSUE TITLE
Cannot install v2.3.4 for Resharper 1.0.2

### ISSUE THREAD

**Issue by sergiorykov** [xunit/resharper-xunit#115]
I have Resharper 1.0.2. Trying to install plugin 2.3.4 from Resharper Extension Manager. Resharper says that it is installed, asks for VS restart and after restart of VS it is still not installed.

**Comment by citizenmatt** [comment]
What symptoms are you seeing that show that it's not installed?

**Comment by sergiorykov** [comment]
Actually - almost nothing. May be Resharper shows download progress too fast and then says it's installed. I've tried several times. 

Are there any logs?

**Comment by citizenmatt** [comment]
Yes, the installer writes a log to `%LOCALAPPDATA%\JetBrains\Shared\v04` for 10.0.2. Feel free to attach, or upload to gist or some such.

**Comment by sergiorykov** [comment]
It's a bit strange - now it shows error: 

> Loading an assembly “JetBrains.ReSharper.Resources, Version=104.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325” which is not listed in assembly references of assembly “JetBrains.ReSharper.Plugins.CyclomaticComplexity, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null” when trying to resolve the type JetBrains.ReSharper.Resources.Settings.CodeInspectionSettings. A type reference points into an assembly not listed among assembly references.

[Installer Log](https://gist.github.com/sergiorykov/3ed67f31e6791c3417a5)

**Comment by citizenmatt** [comment]
Hmm. There's no mention of xunit in the log files. You can safely ignore the Cyclomatic Complexity error - it's the installer getting upset while trying to load the plugin to see if it has custom install steps (it doesn't).

I'd suggest closing all instances of Visual Studio, and going to `%LOCALAPPDATA%\JetBrains\plugins` and delete all `CitizenMatt.Xunit` folders. Then look in the `repositories.config` file in that folder and edit the `packages.config` file(s) it points to, removing any lines that contain `CitizenMatt.Xunit`. Then try and reinstall. That should clear it all up, and hopefully allow it to install.

**Comment by sergiorykov** [comment]
Yeah. It seems it's a bug in Resharper. 
https://resharper-support.jetbrains.com/hc/en-us/community/posts/206009199-Confusing-error-upon-installing-ReSharper-10

I removed plugin `JetBrains.ReSharper.Plugins.CyclomaticComplexity` manually from `%LOCALAPPDATA%\JetBrains\plugins` (it even wasn't listed in installed extensions). And that nasty bug with loading assembly vanished, but plugin hadn't installed. No errors in InstallLog.

I completely uninstalled Resharper - including folders `%LOCALAPPDATA%\Local\JetBrains` and
`%APPDATA%\Local\JetBrains` and restarted Windows.

After _clean_ install of Resharper plugin successfully installed. 

Thank you for your support! 

Unfortunately, I wasn't able to collect enough information why it's occured.

**Comment by shaikhspear16** [comment]
I am facing the same issue. Uninstalling Resharper/ Restarting .. did not help.

Uploading log file. 

[InstallerLog013.txt](https://github.com/xunit/resharper-xunit/files/847400/InstallerLog013.txt)
