### ISSUE TITLE
Plugin not finding test assembly

### ISSUE THREAD

**Issue by j-maly** [xunit/resharper-xunit#116]
When I try to run the tests, I get an error:
Unable to run xUnit.net tests - File not found <ProjectPath>\artifacts\bin\Tests\Tests.dll

This is the contents of artifacts\bin\Tests folder after build: 
<ProjectPath>\artifacts\bin\Tests\Debug\dnx451\Tests.dll
<ProjectPath>\artifacts\bin\Tests\Debug\dnx452\Tests.dll
<ProjectPath>\artifacts\bin\Tests\Debug\dnxcore50\Tests.dll

**Comment by citizenmatt** [comment]
DNX isn't supported right now. We're hoping to get this into ReSharper 10.1, although it also depends on timing with DNX/dotnet-cli releases. I'm closing this in favour of #38
