### ISSUE TITLE
Running a test marked as [Fact] runs tests in the same class marked with [Theory]

### ISSUE THREAD

**Issue by LeahDWood** [xunit/resharper-xunit#117]
When running tests within a solution tests marked with [Fact] will run tests marked with [Theory] within the same class though the result of the Theory tests isn't taken into account.

This has occurred on multiple machines, and within a new solution to check for this issue that consisted of only a simple class and a class containing a Fact and Theory test.

I've checked this with [XUnit's VisualStudio](https://github.com/xunit/visualstudio.xunit) runner but the issue seems isolated to the Resharper integration.

**Comment by citizenmatt** [comment]
Thanks. This is fixed as part of the ReSharper 10.1 support.
