### ISSUE TITLE
when test methods are in base class, traits on a child class, they show as <Uncategorized>

### ISSUE THREAD

**Issue by llehn** [xunit/resharper-xunit#118]
I have this:

```
public abstract class A
{
   [Fact]
   public void TestA()
   {

   }
}

[Trait("Type", "TypeB")]
public class B : A, IClassFixture<FixtureB>
{
 // no test methods here, just the setup for class fixture
}

[Trait("Type", "TypeC")]
public class C : A, IClassFixture<FixtureC>
{
 // no test methods here, just the setup for class fixture
}
```

Unit Test Explorer and Unit Test Sessions show these as uncategorized and the categories Type[TypeB] and Type[TypeC] do not include these tests in the view. However these tests are run by xunit, when I select the whole category and click Run/Debug.

Is this something which can be fixed here or a resharper problem?

**Comment by citizenmatt** [comment]
I've just tested with ReSharper 2016.1.1, and it seems to be working as you'd expect (ReSharper shows both `Type[TypeB]` and `Type[TypeC]`, listing `A.TestA` under both).
