### ISSUE TITLE
Running Nancy tests fails with ArgumentException

### ISSUE THREAD

**Issue by asbjornu** [xunit/resharper-xunit#119]
Trying to run the xUnit tests in [`Nancy.Next.sln`](/NancyFx/Nancy/blob/master/Nancy.Next.sln) with ReSharper, it fails with the following exception:

> **Unit Test Runner failed to run tests**
> 
> Unable to run xUnit.net tests - File not found: C:\Users\aul\Dev\Misc\Nancy\artifacts\bin\Nancy.ViewEngines.Markdown.Tests\Nancy.ViewEngines.Markdown.Tests.dll
> Parameter name: assemblyFileName
> 
> ``` c#
> Exception: System.ArgumentException: File not found: C:\Users\aul\Dev\Misc\Nancy\artifacts\bin\Nancy.ViewEngines.Markdown.Tests\Nancy.ViewEngines.Markdown.Tests.dll
> Parameter name: assemblyFileName
>     at Guard.FileExists(String argName, String fileName)
>     at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticsMessageSink)
>     at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.GetFrontController(TestEnvironment environment)
>     at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.Run(XunitTestAssemblyTask assemblyTask, Boolean disableAllConcurrency)
> ```

Here's a beautiful screenshot of the exception:

![screen shot 2016-03-17 at 14 47 54](https://cloud.githubusercontent.com/assets/12283/13847830/696722c6-ec4f-11e5-9ddc-a8aa4e344ebb.png)

I'm running Visual Studio Enterprise 2015 version `14.0.24720.00` Update 1 with ReSharper version `10.0.2` and xUnit.net extension version `2.3.4`.

**Comment by citizenmatt** [comment]
This error message and the path make it look like you're trying to test DNX, which isn't supported by ReSharper yet. I'm working on getting it implemented in ReSharper 10.1.

I'm going to close this now, if it's not a DNX issue, please reopen.

**Comment by asbjornu** [comment]
@citizenmatt It's DNX, yea. Thanks for the clarification.
