### ISSUE TITLE
dotCover 10.0.2 shows empty coverage when running tests using this extension

### ISSUE THREAD

**Issue by ml054** [xunit/resharper-xunit#120]
I've created empty console application with single method + xunit test for this. After invoking coverage all tests I get empty coverage.

**Comment by citizenmatt** [comment]
I think this is the same as #107. The plugin isn't handling dotCover's settings for shadow copy correctly. You can work around it by disabling shadow copy. Or you can update to 10.1 (currently in EAP), which fixes this and works correctly with shadow copy.
