### ISSUE TITLE
Using dnx version > to 451 makes Unit test disappears from test explorer

### ISSUE THREAD

**Issue by cdie** [xunit/resharper-xunit#121]
Related to this stackoverflow question : http://stackoverflow.com/questions/35626118/why-does-xunit-tests-are-not-visible-in-test-explorer-if-dnx-version-is-to-451

No answers in SO, so I post my question here. Is there a reason ?

I'm using same config as my SO question

```
{
  "version": "1.0.0-*",
  "description": "SESAMEngineFacturation.Tests Class Library",
  "authors": [ "christophe.mom" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "commands": {
    "test": "xunit.runner.dnx"
  },
  "dependencies": {
    "SESAMEngineFacturation": "",
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-*",
    "FluentAssertions": "4.2.2"
  },
  "frameworks": {
    "dnx451": { }
  }
}

```

This make them appear. If I choose dnx460, there not visible (and no compilation error). We want to use dnx460. How can we manage it ?

**Comment by citizenmatt** [comment]
DNX isn't supported yet, it needs changes in ReSharper. I'm hoping to get them done in time for 10.1 (aka 2016.1 in ReSharper's new versioning scheme). Closing this in favour of #38
