### ISSUE TITLE
Missing test runner context icon from gutter

### ISSUE THREAD

**Issue by bibodha** [xunit/resharper-xunit#123]
![screen shot 2016-04-05 at 3 18 26 pm](https://cloud.githubusercontent.com/assets/2340572/14298349/c5cf49e8-fb41-11e5-8ca7-c463f4c01272.png)

I'm missing the dot/icon by my line number (left of the [Fact] attribute) to be able to run a single test. I have xunit test runner for resharper 10 installed and running Visual Studio 2015.

I'm not sure what needs to be turned on or installed. Not sure if this is problem with VS, Reshaper, or xUnit runner. Any help much appreciated. Thank you.

**Comment by citizenmatt** [comment]
That should be all that is necessary - did you restart Visual Studio after installing the extension? Failing that, try making a simple edit to the file, just to force a re-run of the analyser.

**Comment by bibodha** [comment]
I got VS 2015 and resharper 10 a while ago but this has always been a problem. I have restarted multiple times and also edited the test files but the darn dot just doesn't appear. I was hoping it was a quick settings change that I need to do but that doesn't seem to be the case so I filed an issue.

**Comment by citizenmatt** [comment]
You could try clearing the caches for the solution - ReSharper &rarr; Options &rarr; General &rarr; Clear caches. Restart Visual Studio, and ReSharper will rescan everything. Any tests should be rediscovered.

Alternatively, update to the latest ReSharper 2016.1 ([currently in EAP](https://confluence.jetbrains.com/display/ReSharper/ReSharper+10.1+EAP)), this now includes xunit in the box. This would rule out any issues with installing the extension.

**Comment by bibodha** [comment]
Clearing cache didn't help either. I'll just wait for R#2016. Thank you for your assistance.

**Comment by LeahDWood** [comment]
@bibodha Make sure the class is public. It's small but it's something I've missed in the past.

**Comment by bibodha** [comment]
this used to work in vs1013 with R#9. 2015 w/ R#ultimate is when this started happening. all the test classes are marked public.

**Comment by citizenmatt** [comment]
Just to ket you know 2016.1 has been released, so you can install it now and you'll get xunit in the box.

**Comment by citizenmatt** [comment]
Going to close this issue. If it still persists with 2016.1, please raise an issue in the [JetBrains issue tracker](https://youtrack.jetbrains.com).
