### ISSUE TITLE
Ambiguous method name manual test failing as aborted?

### ISSUE THREAD

**Issue by citizenmatt** [xunit/resharper-xunit#15]
Run the tests in the `AmbiguousMethodNames` class in the manual tests solution, and it gets displayed as "aborted", although the tests correctly get reported. Only one of the tests methods with ambiguous names (i.e. `MethodsWithOverridesCannotBeUniquelyFoundByName`) is displayed.

**Comment by 304NotModified** [comment]
I can reproduce this in AppVeyor. See https://ci.appveyor.com/project/304NotModified/nlog/build/4.0.146

In which version is this fixed?
