### ISSUE TITLE
Need to enable MaxDegreeOfParallelism

### ISSUE THREAD

**Issue by stankovski** [xunit/resharper-xunit#18]
Currently there is no way to run tests without multi-threading or to limit the number of concurrent threads. Given that xunit 2.0 runs all tests in parallel this breaks some tests that execute not-thread safe code.

**Comment by citizenmatt** [comment]
The ReSharper runner doesn't manage the threading - that's left to the xunit framework. So, by default, your tests are run in parallel. You can manage this using the standard xunit attributes - using either `[assembly: CollectionBehavior(MaxParallelThreads)]` or `[assembly: CollectionBehavior(DisableTestParallelization = true)]`.

See the [xunit docs for more details](http://xunit.github.io/docs/running-tests-in-parallel.html).
