### ISSUE TITLE
All tests aborted immediately

### ISSUE THREAD

**Issue by megrogan** [xunit/resharper-xunit#23]
Using the latest version all tests abort immediately. The last working version for us is 2.0.0-alpha-20140812.

We are running:
VS 2013 Version 12.0.31101.00 Update 
ReSharper 8.2.3 Full Edition Build 8.2.3000.5176 on 2014-10-09T20:08:24
Windows 7 Professional SP1

**Comment by citizenmatt** [comment]
Fixed in 9125f6647d3613b075f6dc4d521704f96d0fd989. Now reported with an "info bar" in ReSharper 9. Need to backport to ReSharper 8. Will be released shortly.
