### ISSUE TITLE
Tests stay in running state when assertions are not met, instead of just failing

### ISSUE THREAD

**Issue by QFrameTK** [xunit/resharper-xunit#25]
![image](https://cloud.githubusercontent.com/assets/8927289/5813259/06d6dd02-a07b-11e4-8777-f645e59609e9.png)

Sometimes, when a tests fails (example: nhibernate schema validation, automapper assertconfiguration valid, but also business logic tests (are all properties saved to the db, for example), the test runner ends up in a state where it says that the test is still running, and it never gets out of this state anymore (see screenshot). No other tests below these tests in the unit test sessions tree are being executed.

When debugging, you can actually see the assertion failures, and when you then continue the debug session, it ends up in this forever running state as well.

Before, I was using R#8, nothing was wrong. Another dev on my team with R#8 had the issue already. Now we have both upgraded to R#9, and are both facing the issue. 2 other developers on the team don't face the issue, and our CI server (TeamCity) isn't showing this issue either.

My configuration:

- Visual Studio Professional 2013, version 12.0.31101.00 Update-4
-  Resharper 9.0 Update 1 (Build 9.0.2014129.130142)
- XUnit.net Test Support for ReSharper 9 2.0.1

Any clue what might be causing this?

**Comment by citizenmatt** [comment]
What version of xunit are you using in your tests? And do you have a repro for this?

**Comment by QFrameTK** [comment]
Xunit 1.9.2.1705
Unfortunately, this is a private TFS repository for a client. The issue doesn't seem to occur in my own projects, only in this one, for now, so I couldn't reproduce it yet.

**Comment by citizenmatt** [comment]
Is there anything interesting in the way the tests work? Are they async, or use threading, or do they fail in interesting ways?

**Comment by QFrameTK** [comment]
In this case (the automapper configuration), the mappers are configured by Castle Windsor. Then, each mapper is checked to see if their configuration is valid. We have created a testhelper for catching the exception if anything goes wrong. And then FluentAssertions checks if there are any, and if there are, the assertion fails. This all happens, and after failing the assertion, the test keeps running. Nothing special happens there anymore.

Need me to show you some code for all this?

**Comment by citizenmatt** [comment]
It might help, yes please. Are you running just a single test, or all tests in a class?

**Comment by QFrameTK** [comment]
I've made a gist that illustrates our usage. Should be nothing fancy. And again: everything gets executed, even all base classes get disposed. And then the test runner keeps displaying the test as running, and does not run any other tests.

https://gist.github.com/QFrameTK/f6c83753d3c51b56c166

**Comment by citizenmatt** [comment]
That looks brilliant, thanks. Have you tried this code to see if the issue shows up here?

**Comment by QFrameTK** [comment]
Didn't try it, just copied it out of our solution. I'll see if I have time later to isolate this bit and put it in a solution, and see if I can get it to fail... Though I'm not sure if I'll be able to get to that.

**Comment by vertiman** [comment]
I had the same issue, i just grabbed the xUnit plugin source, updated the xUnit libraries and rebuilt and the problem seems to have dissapeared.  QFrameTK - if you want I could send you a nuget package to try to see if it alleviates the issue for you?  If it does, I'll submit a simple pull request with the changes (there were a few API changes in the XUnit SDK).

**Comment by citizenmatt** [comment]
Are you sure that's the same issue? That is, running with RC1 binaries leaves the tests as running? It usually leaves them in an "inconclusive" mode, saying they weren't run, because the runner (built with beta5) can't successfully load the xunit dlls (in RC1, this is because one of the dlls has been renamed).

Either way, I've got a build for RC1 nearly ready, I'll finish it up and get it pushed tomorrow.

**Comment by vertiman** [comment]
I was absolutely having the same issue, tests just kept running (scrolling UI animation, would never end) and I'd have to kill/terminate them.  It only happened when the test failed in some way, and I could see the exceptions thrown when I was debugging, but nothing when I was running.  Also it didn't happen using the MS test runner, just via Resharper.  I'm actually using xUnit 1.x for writing my tests (that's the library I'm referencing anyways).

**Comment by QFrameTK** [comment]
Yep, sounds exactly like the issue I'm facing. Haven't seen the issue in a week, though. What did you change to have it working? I'm definitely interested in the nuget package containing the fix, thanks!
________________________________

**Comment by vertiman** [comment]
I just downloaded source, opened in VS, updated the XUnit references that it built against then rebuilt the solution.  I see your email in the response, I'll email you a link to the nuget package if you want to try it!

**Comment by QFrameTK** [comment]
Thanks!

Sent from my Windows Phone
________________________________

**Comment by vertiman** [comment]
Sent!

**Comment by citizenmatt** [comment]
Very cool, glad you've spotted the issue! When you downloaded and rebuilt, did you use the xunit2 branch? It's the default branch when you go to https://github.com/xunit/resharper-xunit.

**Comment by vertiman** [comment]
No, I used the Resharper 9 branch (since I'm using RS9).

**Comment by QFrameTK** [comment]
Will try using the fix when I face the issue again. Haven't faced it in a while now...

**Comment by QFrameTK** [comment]
Unfortunately, the fix provided to me by @vertiman didn't work. However, it did result in tests staying in pending state instead of running state, but the namespace still stays in running state (see screenshot).

![image](https://cloud.githubusercontent.com/assets/8927289/6039154/3803f10e-ac64-11e4-9484-c53dd4e69962.png)

**Comment by citizenmatt** [comment]
The test session in that picture is still in progress - it hasn't yet completed. Is there a `JetBrains.ReSharper.TaskRunner.{something}.exe` still running in the task manager?

Are any of these tests asynchronous?

**Comment by QFrameTK** [comment]
The tests aren't asynchronous. No task runners are active, currently. I've noticed that these tests are really in a pending state, there's another one that's still in running state (and keeps this state forever). Just started my tests over my lunch break, and it's still running that one test. This one doesn't even do anything exotic, looks exactly like other tests that did succeed. Also, this test has been running for over a week now.

**Comment by citizenmatt** [comment]
For a week! Yikes! I'd suggest restarting Visual Studio. I don't know what's going on, but perhaps it's just got its knickers in a twist, and a restart will help the situation.

**Comment by QFrameTK** [comment]
No, sorry, I mean: this test has been in the project for a week, and has been executed millions of times, and never failed until yesterday. I expressed myself poorly, there.

Also: VS restart doesn't help the situation, the only thing that gets rid of it that I've found is fixing the test to not fail an assertion.

**Comment by citizenmatt** [comment]
Phew! :smile: 

OK, can you try something for me? I can't see what's going wrong, and can't recreated this, so we'll have to try and get an idea of what's up with your situation.

* Debug the test, but make sure you've set up to be notified of all exceptions - Debug → Exceptions, and check the "User-unhandled" and "Thrown" checkboxes for "Common Language Runtime Exceptions"
* Let me know any and all exceptions that happen - especially if they're related to the xunit runner

If that doesn't show anything, try this:

* Start visual studio with "devenv /ReSharper.Internal". This enables some internal commands that help with developing ReSharper.
* Go to ReSharper → Options → Unit Testing and select "Enable Debug"
* Run the failing test. You'll get a message box stating "Waiting for debugger". In Visual Studio, Select Debug → Attach to Process and find the "JetBrains.ReSharper.TaskRunner.{whatever}.exe" and attach to it.
* Make sure you're going to catch all exceptions
* Click OK in the "Waiting for debugger" message box
* Again, keep an eye out for any exceptions.

I'm half expecting a `NullReferenceException` or some such in the runner code - where I'm not handling a response from the test framework properly.

**Comment by citizenmatt** [comment]
I've just pushed a new version to the gallery for both 8.2 and 9.0, that properly supports RC1. It's got a few other fixes and things in there too, so can you try it out and let me know if it you still see the issue?

**Comment by QFrameTK** [comment]
Updated. Will let you know if the issue pops up again...

**Comment by QFrameTK** [comment]
Saw the issue again earlier today. :(

**Comment by citizenmatt** [comment]
Are you using any of the extensibility points? Such as a custom test case orderer, or discoverer, or anything? I think I might have found something related to this.

**Comment by QFrameTK** [comment]
Nothing like that, unfortunately. :(

**Comment by vertiman** [comment]
I upgraded to xunit 2.0rc1 and the problems seem to have gone away. I was
on 1.9 (stable) before. Maybe the problem only happens with legacy support?

**Comment by citizenmatt** [comment]
I'm going to close this. I've rewritten the message handler to be more robust, so it will hopefully handle odd things like this better. I haven't pushed the new version yet (I want to get a couple more fixes in), but when 2.0.6 is released, and the problem remains, please open a new issue.

**Comment by davidchiew** [comment]
I still get this error when on Resharper Ultimate 9.1.3.

Run Units just look like they never end, when I Debug Unit tests the reason is because a Debug.Assert has failed.

**Comment by citizenmatt** [comment]
Can you run `devenv.exe /ReSharper.Internal`, go to ReSharper &rarr; Options &rarr; Unit Testing and enable logging, please? You'll need to create the `%TEMP%\JetLogs` folder, and when you run tests, it'll create a new log file. If you can paste that here, or in a gist, that'd be helpful. Also, can you confirm what version you're on?

**Comment by davidchiew** [comment]
Have tried to get this to happen again, but it seems to be working now. If it happens again I will post the details, thanks for the suggestions.
