### ISSUE TITLE
Tests won't run using latest xUnit 2.0.0-rc1-build2826

### ISSUE THREAD

**Issue by jstew7** [xunit/resharper-xunit#26]
Just says "Inconclusive: Test not run". Looks like there was some breaking change in the RC that requires latest runner. Thanks.

VS 2013 Update 4
ReSharper 9.0 Update 1 Build 9.0.20141219.130142
xUnit 2.0.0-rc1-build2826

**Comment by mayerwin** [comment]
Same here.

**Comment by citizenmatt** [comment]
Yep. I'll get it updated today.

**Comment by johnkors** [comment]
I'm getting "Unknown test framework : Could not find xunit.dll or xunit.execution.dll". Same error?

**Comment by citizenmatt** [comment]
Yep - it'll currently only work with the previous beta. I've got a new build nearly ready for 9.0, need to do a build for 8.2

**Comment by johnkors** [comment]
Okay, thanks. Can't wait to get rid of Vs Test runner.. brr

**Comment by sevenate** [comment]
Looks like (according to commit) this bug is already fixed and that is great, thanks! The only question is - when you think the new plugin version 2.0.2 with the fix for this particular issue will be available in ReSharper's extension manager?

**Comment by citizenmatt** [comment]
Should be fixed for 9.0, haven't yet updated 8.x.They're currently separate codebases. I really, really want to get a new release out, so I'm going to say tomorrow...

**Comment by sevenate** [comment]
OK, great! Thanks for update.
