### ISSUE TITLE
Tests with the same name are omitted

### ISSUE THREAD

**Issue by dzimchuk** [xunit/resharper-xunit#29]
When there are tests with the same name but they are placed in different test classes only one test with a given name will run when we try to run all tests in the project or solution. The rest of them will be skipped (marked with a blue question mark).
It is still possible to run tests in each class be explicitly running them in their classes.

Environment: VS2013 Update 4, R# 9.0 Update 1, latest version of resharper-xunit for that env.

**Comment by citizenmatt** [comment]
I'm not seeing this. E.g. given

```cs
public class Foo
{
    [Fact]
    public void Test1()
    {
    }
}

public class Bar
{
    [Fact]
    public void Test1()
    {
    }
}
```

This definitely executes both tests, and they can both have different results.

Is there anything interesting going on in your situation? Are you using classes in the same namespace? What grouping options have you got? And what version of xunit are you using?

**Comment by dzimchuk** [comment]
I'm afraid it was a bit prematurely to open up the ticket. I've tried to reproduce this in other projects and all tests were run as expected.

The project where I had this strange behavior had some Autofac setup in test classes. However I don't see how it could affect things (yet).

In all cases xunit 1.9.2 was used.

I'm closing it until I have some new information.
