### ISSUE TITLE
xUnit runner persistently does not work

### ISSUE THREAD

**Issue by SurajGupta** [xunit/resharper-xunit#31]
Across clean installs (OS - Win 8.1 and Visual Studio 2013 - various updates up to and including update 4) and multiple machines, I've found the xunit runner to be extremely unreliable.  Sometimes it works.  Sometimes the chevrons next to each test don't show up.  Sometimes they show up, but clicking debug or release does nothing.  Sometimes clicking on debug/release looks like it's attempting to do something, but then does nothing.  Sometimes, right-clicking on a test class and running all tests works, sometimes it doesn't.  I cannot isolate the factors that contribute to whether it will fully work or not.  Right now I have Resharper 8.2.3000.5176 installed.

Other developers on my team have had the same experience.  We don't have any company-mandated config, these are all independent machines running individual copies of VS, etc.

So I guess this is a bug, but moreso it's a plea for help.  What can I do to make the resharper x-unit runner stable and reliable?  Right now I'm forced to use the built-in VS test runner which totally sucks in comparison to the re-sharper plug-in (when it works).  I'm happy to provide any additional info.

**Comment by citizenmatt** [comment]
Unfortunately, I don't see any of these issues - it's much better behaved for me than what you've described. If you could find some kind of repro, it would really help. Sorry to not be more helpful, but without more info, and not being able to repro this myself, I'm afraid there's not much I can do.

**Comment by SurajGupta** [comment]
I'll try to create a repo.  On the same machine, I have solutions where the runner will work and others solutions where the runner will not work.  And sometimes the same solution starts or stops working.  For example, a solution I was working on yesterday did not work when using the green/yellow dots, but did when I ran tests from the Unit Test Explorer.  I stopped using the dots and continued developing.  This morning, just for kicks I tried the dots and now they work!  I'm not sure how I'll isolate the state where the runner fails, but I'll try.

**Comment by citizenmatt** [comment]
Any news?

**Comment by SurajGupta** [comment]
Would you be available for a screenshare?  I can't figure out when and why it works or doesn't work, but you really have to see it to believe it.  Maybe we could put our heads together and figure it out.  If so, could you propose some days/times next week that work for you and I can setup a GoToMeeting.

**Comment by citizenmatt** [comment]
Closing as can't repro.

**Comment by SurajGupta** [comment]
??  I proposed we do a screenshare so you can see what's happening.

**Comment by citizenmatt** [comment]
Sorry, that was nearly 6 months ago. Apologies for not following up. I take it this is still an issue? I don't think I'll be able to do a screenshare - how about capturing a short screencast? I don't have 8.2 installed any more (I'm mostly targeting 9.1 + the 9.2 EAPs right now). Have you tried v9?

One thing you can try and do is enable logging for when you run tests.

* Run Visual Studio with ReSharper in internal mode: `devenv /ReSharper.Internal`
* Go to ReSharper &rarr; Options &rarr; Unit Testing and check "Enable Logging"
* Make sure the `%TEMP%\JetLogs` folder exists
* Run the tests. Each time the tests are run, a file is written to `%TEMP%\JetLogs`. When you get a run where they don't work, get the latest file and attach it to the issue.

**Comment by SurajGupta** [comment]
v9 seems to work well in some initial testing.  Lets just close this out and if I'm still having issues I can open a new bug and follow the steps you listed.
