### ISSUE TITLE
Tests won't run with xUnit 2.0.0-rc2

### ISSUE THREAD

**Issue by Hinidu** [xunit/resharper-xunit#33]

**Comment by thejoshcrawford** [comment]
I'm having this issue as well. I'll add a few more details on the error I'm getting. 

When attempt to run a test with the Resharper Test Runner I get "Unable to run xUnit.net tests - The path is not a legal form." and have an exception was thrown from XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.GetAssemblyFolder(...)

**Comment by Hinidu** [comment]
@citizenmatt thanks for the fix! Could you please upload this version to resharper plugins gallery?

**Comment by citizenmatt** [comment]
Nope :)

I was going to, but then RC3 got released yesterday. I'll release an RC3 compatible version today.

**Comment by Hinidu** [comment]
Damn, I didn't notice RC3 yet=\ Thank you!
