### ISSUE TITLE
Inconclusive: Test not run

### ISSUE THREAD

**Issue by gabrielweyer** [xunit/resharper-xunit#34]
I'm using:
 - Visual Studio 2013 Professional Update 4
 - xUnit.net Test Support for ReSharper 9 (2.0.2)
 - JetBrains ReSharper 9.0 Update 1 Build 9.0.20141219.130142
 - xunit 2.0.0-rc2-build2857
 - xunit.abstractions 2.0.0-rc2-build2857
 - xunit.assert 2.0.0-rc2-build2857
 - xunit.core 2.0.0-rc2-build2857
 - xunit.extensibility.core 2.0.0-rc2-build2857

I can't run any of my unit tests (`[Fact]` or `[Theory]`), all the tests are marked as inconclusive.

This is the error message I get:

`Unable to run xUnit.net tests - Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found.`

![unit-test-runner](https://cloud.githubusercontent.com/assets/2101647/6280297/d6dc96cc-b8fe-11e4-9af5-a6b3966e9305.png)

**Comment by citizenmatt** [comment]
The answer's in the screenshot :smile: The current version requires you use xunit RC1, not RC2 - there have been breaking changes, and the plugin doesn't support RC2 yet. See #33

**Comment by gabrielweyer** [comment]
Oh my bad, I understood the message differently. I assumed it was saying that xUnit.net requires a specific version of the xUnit runner for ReSharper. As I just updated my xUnit ReSharper runner it didn't make much sense.

Maybe you could rephrase the error message to something like this:

`xUnit.net ReSharper runner requires xUnit.net 2.0.0-rc1-build2826`

**Comment by citizenmatt** [comment]
Yep, that sounds like a good idea.
