### ISSUE TITLE
Tests don't seem to run when the project is hosted on a network share

### ISSUE THREAD

**Issue by amithgeorge** [xunit/resharper-xunit#41]
Using Visual Studio 2013 Community, Resharper 8.2.3. One Class library project. It has the nuget references for xunit, xunit VS runner. The xunit extension for R# is also installed. 

When opening the project from a network drive,
   - The VS test explorer simply doesn't detect the tests
   - Resharper shows the icons next to the test. Running the test seems to do something. Not sure what, but the test runner UI shows that its processing and it remains that way till manually stop the test execution. Bottomline, the test doesn't run, no pass/fail message. 
   - After failing to execute the tests, I uninstalled the xunit VS runner and installed xunit console runner. I am able to execute the tests properly from the console. 

When opening the project from a local c: drive (after copying the files over)
   - Both test runners (VS & R#) run the tests properly and immediately. I uninstalled the console runner from the previous run and reinstalled the VS runner. 

Any ideas on how to make this scenario work with the R# runner? I am on a Macbook (Mavericks), running Windows 8.1 using Parallels. I prefer the files being accessible from OSX and not isolated to the windows drive inside Parallels.

**Comment by citizenmatt** [comment]
Yeah, this is a .net thing - trust issues because we're loading and running assemblies from the network. I don't believe there's anything can be done to fix this issue - you have to run locally. But I'll see if there's anything that can be done to at least fail gracefully.

**Comment by citizenmatt** [comment]
Out of interest, what happens if you run the tests with the xunit command line runner? In particular, when the command line runner is local, but the test assembly is on the network share?

**Comment by citizenmatt** [comment]
Also, what version of the runtime are you targeting? .net 4 or .net 2/3.5?

**Comment by amithgeorge** [comment]
> Out of interest, what happens if you run the tests with the xunit command line runner? In particular, when the command line runner is local, but the test assembly is on the network share?

From what I understand the xunit console runner is installed via nuget into the same folder as the solution. While both the solution and the console runner is on the network share, the runner executes the tests fine. I copied the runner files to C:\ and tried again. The runner is still able to run the tests. Z:\ is the mapped network drive. 

    Z:\RedditDailyProgrammer\src\RedditDailyProgrammer> C:\xunit.runner.console.2.0.0\tools\xunit.console.exe .\bin\Debug\RedditDailyProgrammer.dll
    xUnit.net console test runner (64-bit .NET 4.0.30319.34014)
    Copyright (C) 2015 Outercurve Foundation.

    Discovering: RedditDailyProgrammer
    Discovered:  RedditDailyProgrammer
    Starting:    RedditDailyProgrammer
    Finished:    RedditDailyProgrammer

    === TEST EXECUTION SUMMARY ===
      RedditDailyProgrammer  Total: 26, Errors: 0, Failed: 0, Skipped: 0, Time: 0.656s

The solution is targeting .Net 4.5.1. When you mention trust issues, you mean there is no Windows setting or "Unblock" equivalent that I can use?? 

If the issue is only with loading assemblies over the network, I can instead change the Project properties to output the binaries to a local C:\ folder. Heck, I just went ahead and did that. I am able to run the tests using the R# test runner!! 

Bottomline - Keep the source files on the network share. Modify the project properties to output the binaries to a local drive. Run tests.

**Comment by citizenmatt** [comment]
Thanks for trying it out!

There isn't an "unblock" setting. You might be able to alter CAS policy to allow this to be fully trusted. But if the xunit console runner can work, the resharper runner should also be able to work just fine...

**Comment by amithgeorge** [comment]
Hmmm. The R# runner definitely doesn't work when the binaries are on the network path. For the time being, I am able to resolve my issue by setting the build output to a local drive folder. 

If you feel there is nothing that can be done to enable the R# runner to work with network path assemblies, then you may close this issue.

**Comment by citizenmatt** [comment]
Thanks, I'll leave it open, though. I'm glad you've got a workaround, but if the xunit console runner can work, I don't see why I shouldn't be able to get the resharper runner to work. I'll have a dig around.

**Comment by citizenmatt** [comment]
I can't recreate this, also using Parallels and with a project on the shared parallels drive. I get prompted when loading the solution that it's from an untrusted source, blah blah blah, but it loads and tests are found, and run correctly. I'm using ReSharper 8.2 + 9.1 EAP, xunit 2.0 RTM and my latest build of the plugin (which has significant changes, but nothing that should affect assembly loading and trust).

I'm going to close this now. When 2.0.6 is released in the next day or so, could you test again, and see if it works?
