### ISSUE TITLE
Static test class

### ISSUE THREAD

**Issue by Maxwe11** [xunit/resharper-xunit#46]
Couldn't run tests if tests class is `static`.
R# 9.0

**Comment by citizenmatt** [comment]
Tests in static classes work - are you making your static class public? It doesn't work if the class is private.

**Comment by Maxwe11** [comment]
![r9_0](https://cloud.githubusercontent.com/assets/1083827/7091928/4f916f4c-dfb6-11e4-936d-74210d5ab619.gif)

**Comment by citizenmatt** [comment]
Ah, I see. Yep. This is an issue. It's because the in-editor discovery is still based on xunit1, and that doesn't support static classes. It'll be a little while before it'll be reimplemented, sadly.
