### ISSUE TITLE
Can't run one test only in one class

### ISSUE THREAD

**Issue by arashk1368** [xunit/resharper-xunit#48]
Hi,
After I updated the extension to 2.0.6-alpha, I am not able to run a test separately in a class. Whenever, I run or debug, it runs all the tests.

**Comment by citizenmatt** [comment]
This is an issue with the 2.0.6-alpha. I'm just about to push an update - 2.0.6 for ReSharper 9.0 and 2.1.6 for ReSharper 9.1. It fixes this issue.

**Comment by citizenmatt** [comment]
Just pushed. Should be available to update now.

**Comment by arashk1368** [comment]
I updated and it fixed the issue.
Thanks
