### ISSUE TITLE
When debugging a single test MemberData is generated for tests that are not being run

### ISSUE THREAD

**Issue by dbraaten42** [xunit/resharper-xunit#49]
using Xunit;
using System.Threading;

namespace XUnitTestRunnerBug
{
    public class Class1
    {

        [Theory, MemberData("GetSomeData")]
        public void Test(string somedata) {}

        public static string GetSomeData()
        {
           Thread.Sleep(Timeout.Infinite);
            return "Test";
        }

        [Fact]
        public void Test2()
        {
            Assert.True(true);
        }
    }
}

Using the test runner if you debug or run Test2.  GetSomeData is executed, I would not expect it to be run as the test it is required for is not being run.  
This is an issue for me because I have a number of tests were the data generation takes a long time and I don't want to run it for tests  that I am not actively debugging.

**Comment by bradwilson** [comment]
It runs during discovery, because theory data is pre-discovered by default (so that users can run individual rows of data, rather than being forced to run all data rows).

You can override the default using `App.config`: http://xunit.github.io/docs/configuration-files.html

**Comment by bradwilson** [comment]
Sorry, I didn't pay attention to whose project this was, and shouldn't have closed the issue. :disappointed:

**Comment by citizenmatt** [comment]
I was about to post exactly the same answer as you, and close the issue. You beat me by seconds :grinning: 

@dbraaten42, I'm going to close the issue again, as this is the answer - disabling pre-enumeration of theories. Or at least it should be - feel free to reopen if it doesn't solve things.
