### ISSUE TITLE
Installing specific version of xunit runner

### ISSUE THREAD

**Issue by rballa** [xunit/resharper-xunit#51]
How can I install a specific version of xunit runner? Any way other than through Visual Studio?

Thanks
Rajesh

**Comment by aweiker** [comment]
You can specify the version in the packages.config file and then a nuget restore will use that specific version.

**Comment by citizenmatt** [comment]
Not for the resharper runner. You pretty much have to install the latest version. Why do you want to install a previous version?

**Comment by citizenmatt** [comment]
Closing this for now. Reopen if it's still required...
