### ISSUE TITLE
Cannot find in resharper extension gallery

### ISSUE THREAD

**Issue by jonathanmendez** [xunit/resharper-xunit#52]
I was trying to set up our intern's computer today, and we couldn't find this in Resharper's extension manager. Indeed, going back to my machine (where I have it installed), I cannot find it in my extension manager there either. (We did make sure to include prerelease).
We have Resharper 8.2.
As far as I can tell from browsing your various pages, this isn't something you've announced as intentional. Did some glitch get it kicked out of the extension manager?

**Comment by citizenmatt** [comment]
Yes, there's a bug in the gallery that means that 8.2 extensions fall out of the index. I need to get a fix done, but haven't had any time to do this so far. I'm rebuilding the index fairly frequently, so it should be there. If not, you can ping me on twitter - [@citizenmatt](https://twitter.com/citizenmatt)
