### ISSUE TITLE
Support for traits defined on base classes

### ISSUE THREAD

**Issue by karolwaledzik** [xunit/resharper-xunit#53]
Hi,

thanks for the great plugin. One feature I am missing is support for traits defined on abstract base classes of tests. These are currently not picked up by Resharper (at least with XUnit 1.9.2, which I am still using because of performance problems with v2).

Actually, I even have a fix for this problem. Sorry for not making a pull request, but I didn't have a chance to test it properly with all Resharper-XUnit version combinations.
Anyway, the only change needed to make it work (at least for Resharper 9 / xunit v1) is replacing MetadataTypeInfoAdapter.GetCustomAttributes method with this implementation:

public IEnumerable<IAttributeInfo> GetCustomAttributes(Type attributeType)
        {
            var current = metadataTypeInfo;
            while (current != null)
            {
                foreach (var attribute in (from attribute in current.CustomAttributes
                                           where attributeType.IsAssignableFrom(attribute.UsedConstructor.DeclaringType)
                                           select attribute.AsAttributeInfo()))
                {
                    yield return attribute;
                }
                current = (current.Base == null) ? null : current.Base.Type;
            }
        }

**Comment by citizenmatt** [comment]
Thanks for the code snippet! Traits on base classes are currently working in 9.2 and 10.0
