### ISSUE TITLE
Not available in Resharper 8.2

### ISSUE THREAD

**Issue by sbloedel** [xunit/resharper-xunit#54]
I've just upgraded computers and installed Resharper 8.2.0.2160.

If I go to Resharper's Extension Manager RESHARPER -> Manage Extensions, and search for Xunit.net, I cannot find the plugin.  xUnit.net Test Support cannot be found in the online extensions.

Thoughts?

**Comment by citizenmatt** [comment]
There's an annoying bug in the gallery that causes items to be lost in the 8.2 feed. I have to rebuild the index to get it working again. I think I've got a fix, need to test it a bit more, will hopefully deploy next week. In the meantime, I've kicked the index, can you try again? If it's not there, you can ping me on twitter - [@citizenmatt](https://twitter.com/citizenmatt) and I should be able to rebuild the index right then. Apologies...

**Comment by djhmateer** [comment]
Hi Matt - I'm seeing the same behaviour too.  Have pinged you.  Am on R# 8.2.3000.5176 on VS2013

**Comment by citizenmatt** [comment]
Yep. Site is down, just chasing down getting it restarted.

**Comment by djhmateer** [comment]
Thanks Matt.  Upgraded R# to latest and all works again :-)

**Comment by dzendras** [comment]
The issue still persists...

**Comment by citizenmatt** [comment]
Sadly, yes. I'm testing a fix today.

**Comment by dzendras** [comment]
I've just installed it :)

**Comment by knunery** [comment]
I am having this issue too. I have Resharper 8.2.2 installed and cannot see xunit related packages in the Resharper extension manager.

**Comment by jmkelly** [comment]
I'm seeing this issue as well (Resharper 8.2.0.2160).

**Comment by citizenmatt** [comment]
Sorry. Just rebuilt the index. Try again.

**Comment by knunery** [comment]
Index rebuild didn't work for me. Upgraded to latest version of Resharper.

**Comment by ivanmartinvalle** [comment]
This is still an issue for me also. I previously had ReSharper version 8.2.0.2160, then tried the update to 8.2.3000.5176, and it still didn't work.

**Comment by citizenmatt** [comment]
Just rebuilt the index. Try again.

**Comment by ivanmartinvalle** [comment]
Fix confirmed! Thank you!

**Comment by citizenmatt** [comment]
A bug fix was pushed to the server today. The index appears stable, so I'm closing this issue.
