### ISSUE TITLE
"Test not run" Resharper 9.1 in VS 2015 RC

### ISSUE THREAD

**Issue by Magnus12** [xunit/resharper-xunit#55]
All test are discovered but when trying to run them it just says "inconclusive: Test not run".
Running the test in VS test explorer works.
![test](https://cloud.githubusercontent.com/assets/12508860/7809782/0bdc90c8-039d-11e5-97e9-18cb719f9144.png)

**Comment by citizenmatt** [comment]
Are you using the latest version of the plugin? It should be version 2.1.7.

If you are, can you run with logging enabled?

* Start Visual Studio with ReSharper in internal mode: `devenv /ReSharper.Internal`
* Go to ReSharper &rarr; Options &rarr; Unit Testing and check Enable Logging
* Create the `%TEMP%\JetLogs` folder
* Run the tests

The test runner will generate a log file in `%TEMP%\JetLogs` detailing what it's done. Can you post that so we can see what's going on?

**Comment by Grinderofl** [comment]
I'm experiencing the same issue (except for me, even VS test explorer doesn't work...):

```
23:12:29.220: 1: Connecting to 127.0.0.1:8078
23:12:29.225: 1: Waiting for tasks.
23:12:29.238: 3: Configuration received: <configuration><runner-paths /><runner-infos><runner-info id="xUnit" code-base="xunitcontrib.runner.resharper.runner.9.1.DLL" type-name="XunitContrib.Runner.ReSharper.RemoteRunner.XunitTaskRunner" /></runner-infos></configuration>
23:12:29.239: 3: Using JetBrains.ReSharper.TaskRunnerFramework.DummyClientController
23:12:29.268: 5:Runner thread: Processing packets
23:12:29.268: 5:Runner thread: <task-start />
23:12:29.271: 5:Runner thread: Executing 1 root tasks
23:12:29.272: 5:Runner thread: Loading TaskRunner xUnit (XunitContrib.Runner.ReSharper.RemoteRunner.XunitTaskRunner) from file:///C:/Users/Nero/AppData/Local/JetBrains/Installations/ReSharperPlatformVs14_000/xunitcontrib.runner.resharper.runner.9.1.DLL
23:12:29.275: 5:Runner thread: <task-start><task task-type="XunitContrib.Runner.ReSharper.RemoteRunner.Tasks.XunitBootstrapTask, xunitcontrib.runner.resharper.runner.9.1, Version=2.0.6.25609, Culture=neutral, PublicKeyToken=null" runnerID="xUnit" id="8a7a176a-bceb-4715-9065-ec490625704f" ProjectId="946884C9-B569-4772-AC6F-2D7244975D52" /></task-start>
23:12:29.294: 5:Runner thread: <task-exception type="System.ArgumentException"><task task-type="XunitContrib.Runner.ReSharper.RemoteRunner.Tasks.XunitBootstrapTask, xunitcontrib.runner.resharper.runner.9.1, Version=2.0.6.25609, Culture=neutral, PublicKeyToken=null" runnerID="xUnit" id="8a7a176a-bceb-4715-9065-ec490625704f" ProjectId="946884C9-B569-4772-AC6F-2D7244975D52" /><message>The path is not of a legal form.</message><stack-trace>   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestEnvironment.GetAssemblyFolder(TaskExecutorConfiguration config, XunitTestAssemblyTask assemblyTask)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestEnvironment..ctor(XunitTestAssemblyTask assemblyTask)
   at XunitContrib.Runner.ReSharper.RemoteRunner.TestRunner.Run(XunitTestAssemblyTask assemblyTask)
   at XunitContrib.Runner.ReSharper.RemoteRunner.XunitTaskRunner.ExecuteRecursive(TaskExecutionNode node)
   at JetBrains.ReSharper.TaskRunnerFramework.StartupTaskRunnerHost.Execute(TaskExecutionNode node)</stack-trace></task-exception>
23:12:29.294: 5:Runner thread: <task-finish result="Exception"><task task-type="XunitContrib.Runner.ReSharper.RemoteRunner.Tasks.XunitBootstrapTask, xunitcontrib.runner.resharper.runner.9.1, Version=2.0.6.25609, Culture=neutral, PublicKeyToken=null" runnerID="xUnit" id="8a7a176a-bceb-4715-9065-ec490625704f" ProjectId="946884C9-B569-4772-AC6F-2D7244975D52" /><message>ArgumentException: The path is not of a legal form.</message></task-finish>
23:12:29.294: 5:Runner thread: Finished processing packets
23:12:29.295: 5:Runner thread: <task-finish result="Success" />
23:12:29.298: 3: Closing server
```

**Comment by citizenmatt** [comment]
@Grinderofl is this an asp.net 5/DNX test? The exception indicates that the plugin has the wrong path to the assembly. If you're trying to run a DNX test, this path is likely to be invalid, as DNX does testing without compiling an actual .dll to disk.

**Comment by somewhatabstract** [comment]
I have the same issue. Not using DNX.

**Comment by citizenmatt** [comment]
Can you get a trace for the mstest issue for me, please? I can see if it's related, and if not I can forward to the ReSharper issue tracker.

**Comment by somewhatabstract** [comment]
I'll see what I can do. I tracked down the main part of my issue to a workaround I had installed to get code-based test data to work in MSTest (as we know, MSTest is horrible...just need time to migrate to xUnit). I stopped using that workaround and things started working. However, in principle, the workaround should be working - so I'll try to whip up a test project that exhibits the issue and get back to you.

**Comment by Sequenta** [comment]
Hi,
I'm using xUnit 2.0.0, Visual Studio 2015 (Release version) and ReSharper 9.1.1 
Test runner stopped to recognize Theory, tests became unconclusive. In logs I see
```
15:33:11.918: 8: Discovered: «UnitTests.Web.Site.AccountControllerTests.LogIn_ByPassword_Success - UnitTests.Web.Site.AccountControllerTests.LogIn_ByPassword_Success (d860e37fb3e4e964cdb87fbce8886e15b5a81543)»
15:33:11.920: 8:  Test case is NOT a requested method: «UnitTests.Web.Site.AccountControllerTests.LogIn_ByPassword_Success - UnitTests.Web.Site.AccountControllerTests.LogIn_ByPassword_Success (d860e37fb3e4e964cdb87fbce8886e15b5a81543)»
15:33:11.921: 8:  Test case class unknown. Cannot be a dynamic test of a requested class. UnitTests.Web.Site.AccountControllerTests - «UnitTests.Web.Site.AccountControllerTests.LogIn_ByPassword_Success - UnitTests.Web.Site.AccountControllerTests.LogIn_ByPassword_Success (d860e37fb3e4e964cdb87fbce8886e15b5a81543)»
```

**Comment by Sequenta** [comment]
Fixed by updating version of AutoFixture in app.config.

**Comment by citizenmatt** [comment]
Glad it's working. If there are any other issues, please reopen.

**Comment by daviddvora** [comment]
This also happened to me, and found the solution that actually worked in here:
http://www.henrikbrinch.dk/Blog/2012/02/15/Making-Resharper-testrunner-work-in-64-bit

Hope this will help you

**Comment by citizenmatt** [comment]
Ouch. That's a pretty nasty "fix". ReSharper already ships with both 32 and 64 bit versions of the test runner executables. It will pick one up automatically depending on the bit-ness of your test project (so it needs to be the same as your system under test, or you'll get a `BadImageFormatException`). But you can also force it via the options - specify which version of the .net framework to target, and which bit-ness to use. That's a much better option that copying and renaming executables. I'll add a comment to that blog post, too.

**Comment by daviddvora** [comment]
Thanks
