### ISSUE TITLE
Annotations not working when using xunit.assert.source?

### ISSUE THREAD

**Issue by EnCey** [xunit/resharper-xunit#56]
We use a couple of custom `Assert` methods and follow xunit's [recommendation](http://xunit.github.io/docs/nuget-packages.html) of using the `xunit.assert.source` NuGet package to get the assert source.

The external ReSharper annotations do not seem to work for our Assert methods (like `[NotNull]` on `Assert.NotNull()`). 

Is it possible to make the annotations work with Asserts in source form? The namespace is still `Xunit`, if that has anything to do with it.

**Comment by citizenmatt** [comment]
Sadly, no. External annotations can only work with compiled code. To get them working in the source, you'd need to add them to source. I wonder if there's anything I can do to get a quick fix to help out here...

**Comment by EnCey** [comment]
If we were to put the assert source in a separate project and reference the compiled DLL instead, could we get it running then?

**Comment by citizenmatt** [comment]
Not automatically. It's keyed on the assembly name. But you could deploy the .xml file next to your .dll and it should work then. You'll need to name it correctly, and edit the assembly name at the top of the file. If your .dll is called `myxunit.dll`, you'll need to rename the file to `myxunit.ExternalAnnotations.xml`.

**Comment by EnCey** [comment]
Would that be the [xunit.assert.xml](https://github.com/xunit/resharper-xunit/blob/xunit2/resharper/ExternalAnnotations/xunit.assert.xml)?
I'll give it a try, thanks for the help!

**Comment by citizenmatt** [comment]
Ah, yes, should have linked to it. That's the one, change the name of the file to end `{…}.ExternalAnnotations.xml` and change the `name` attribute to match the .dll name. Note that it will need to be in place when the solution is opened - it's not monitored for changes. Or you can remove and add the reference, that should also re-read the annotations file.
