### ISSUE TITLE
Runner doesn't work when ReSharper is installed for all users

### ISSUE THREAD

**Issue by StevenLiekens** [xunit/resharper-xunit#57]
I installed ReSharper for all users using the administrative install option.

````
JetBrains.ReSharperUltimate.2015.1.1.exe /VsVersion=10;11;12;14 /SpecificProductNames=ReSharper /Silent=True /PerMachine=True 
````

Now, ReSharper doesn't find any of my tests. I assume that means this is not a supported setup in the current version of the extension.

**Comment by citizenmatt** [comment]
Good question. I haven't tested this configuration. Does the extension manager say it's installed?

**Comment by StevenLiekens** [comment]
All looks fine in the extension manager.

**Comment by citizenmatt** [comment]
Do you have any other extensions installed? Do they work?

**Comment by StevenLiekens** [comment]
I just tried this on another machine at home. Same thing. The runner doesn't work when ReSharper is installed in %programfiles% instead of %localappdata%. I don't know about other extensions.

**Comment by citizenmatt** [comment]
Hmm. What's the install folder under Program Files? Does it contain `xunitcontrib.runner.resharper.provider.dll` and `xunitcontrib.runner.resharper.runner.dll` (or something like it - I can't remember the exact names :smile: )

**Comment by StevenLiekens** [comment]
I don't know why, but the installer created two folders for VS2013 on my work laptop

C:\Program Files (x86)\JetBrains\Installations\ReSharperPlatformVs12
C:\Program Files (x86)\JetBrains\Installations\ReSharperPlatformVs12_001

Neither folder contains the xunitcontrib libraries.

**Comment by citizenmatt** [comment]
Hmm. I've asked internally, and will have to check with a clean install of ReSharper for all users. This might take a couple of days, though. Sorry...

**Comment by StevenLiekens** [comment]
I'm not testing with a clean install. I uninstalled ReSharper for my user, then reinstalled for all users.

**Comment by citizenmatt** [comment]
Yep. That's what I meant - uninstall and reinstall.

**Comment by StevenLiekens** [comment]
Oh, well, clean reinstall usually means deleting all junk that is created while using the program (temp files and settings).

**Comment by StevenLiekens** [comment]
Crap. I reinstalled ReSharper for just my user, and it still won't work.

**Comment by citizenmatt** [comment]
Did you uninstall the extension and reinstall? It's looking like it's a bug in ReSharper not working with extensions when it's installed in all users mode. And it's likely that the extension will need to be reinstalled to make it work with a per-user install.

**Comment by StevenLiekens** [comment]
I did that a few times, but that didn't change anything. :/

**Comment by citizenmatt** [comment]
And are you restarting VS after installing? As long as there aren't any installations in program files, and as long as the xunitcontrib files are in the AppData installation folders, you should be back on track.

**Comment by StevenLiekens** [comment]
Thanks. That works. :)

**Comment by citizenmatt** [comment]
This seems to be a bug in ReSharper, rather than the xunit runner. I'm going to close this issue for now. Here's the bug against ReSharper: https://youtrack.jetbrains.com/issue/RSRP-440882

**Comment by StevenLiekens** [comment]
Okay, sweet :)

**Comment by StevenLiekens** [comment]
Was this fixed for 9.2?

**Comment by citizenmatt** [comment]
I haven't tested it, but yes, I believe it is.

**Comment by StevenLiekens** [comment]
Okay, cool. :)

Is it safe to delete `%localappdata%\JetBrains` if I plan to install for all users?

**Comment by citizenmatt** [comment]
There are caches and settings and other run time data stored in there, too. If you delete `%LOCALAPPDATA%\JetBrains`, you'll delete all of that too (the caches will get recreated, but you'll lose any settings). You can just delete `%LOCALAPPDATA%\JetBrains\installations`, which is the all the installed binaries. Although it's probably easier to actually uninstall from add/remove programs.
