### ISSUE TITLE
Not finding all tests

### ISSUE THREAD

**Issue by drewnoakes** [xunit/resharper-xunit#60]
From my test project's context menu, choosing Run Tests doesn't cause all tests to be added to the unit test session.

Even if I clear down the session, retrying cause only a subset of test classes to be included.

If I open one of the missing test classes in the editor and retry, that one test class will be added to the session. The class's document may be closed before running the tests and it'll still be added to the session.

---

I'm using resharper-xunit 2.0.7 and the following packages:

    <package id="xunit" version="2.0.0" targetFramework="net45" />
    <package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
    <package id="xunit.assert" version="2.0.0" targetFramework="net45" />
    <package id="xunit.core" version="2.0.0" targetFramework="net45" />
    <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />

**Comment by drewnoakes** [comment]
I found that clearing the R# caches and restarting VS helped. All tests were added to the session.

I'll report back if I see this again. Let me know if there's anything I should check.

**Comment by citizenmatt** [comment]
What version of ReSharper are you on? There was an issue where the Run Tests right click didn't work correctly (but I can't remember which version - 9.0 perhaps?). So I'd suggest installing 9.1.1, the latest version.

**Comment by citizenmatt** [comment]
Closing. If issue still occurs, please reopen.

**Comment by drewnoakes** [comment]
Apologies for radio silence on this. I wasn't able to repro it in the end, but will ping back if it occurs again.

Thanks for your work on this extension.
