### ISSUE TITLE
Nullable return value in generic interface implementation

### ISSUE THREAD

**Issue by Pondidum** [xunit/resharper-xunit#61]
I have come across an interesting problem with nullable types in interfaces while debugging tests under the resharper runner in visual studio.

## Reproduction

This test will **fail** if:
* You *debug* in the resharper runner, set a breakpoint on `var test = store.GetLatestSequenceFor(Guid.NewGuid());`

This test will **pass** if:
* You run it in the console runner
* You run it in the resharper runner
* You *debug* it in the resharper runner, but don't set a breakpoint
* You *debug* it in the resharper runner, and step into the implementation or `GetLatestSequenceFor`
* You change the `DoTest` arguement to be `TestEventStore`, and do the fail step
* You remove the generic type parameter (change just to Guid etc.)
* Create a console application, with the same code, but the `Main` method instead of the `Fact` method
* You *debug* under the visualstudio runner 
```c#
public interface IEventStore
{
	int? GetLatestSequenceFor<TKey>(TKey aggegateID);
}

public class TestEventStore : IEventStore
{
	public int? Value { get; set; }

	public int? GetLatestSequenceFor<TKey>(TKey aggegateID)
	{
		return Value;
	}
}

public class Tests
{
	[Fact]
	public void When_faking_a_value()
	{
		DoTest(new TestEventStore());
	}

	public void DoTest(IEventStore store)
	{
		var test = store.GetLatestSequenceFor(Guid.NewGuid());

		Assert.Equal(null, test);
	}
}
```

## Versions

Packages:
```xml
<package id="xunit" version="2.0.0" targetFramework="net45" />
<package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
<package id="xunit.assert" version="2.0.0" targetFramework="net45" />
<package id="xunit.core" version="2.0.0" targetFramework="net45" />
<package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />
```

Project:
.Net Framework 4.5, Class library, AnyCpu, Debug mode.

**Comment by citizenmatt** [comment]
I can't recreate this. It just debugs normally and passes the test. I'm using VS2013, ReSharper 9.1.1 and xunit runner 2.1.7.

And I can't think of any reason why this would happen - especially if the test passes when you step into the method. The only thing that would be different is that perhaps the JIT is compiling code differently when you step in to stepping over. And if we're at the JIT level, then I'm over my head :smile: 

Are you doing anything else interesting, or is it just the sample code you've posted? Are you trying to debug all tests and there are some others running concurrently that might be interfering and causing the test to fail? Perhaps the debugger is slowing things down enough to introduce a race condition that can cause the test to fail?

**Comment by Pondidum** [comment]
I thought it might have been something similar like other tests etc, but no - I created a brand new project with just the above code in it, and still had the problem.

I'll push the repo up to github when I get back to my laptop, and note down all my version numbers too.

**Comment by Pondidum** [comment]
Repository: 
* https://github.com/Pondidum/XunitBug

Versions:
* Microsoft Visual Studio Ultimate 2013, Version 12.0.31101.00 Update 4
* Microsoft .NET Framework Version 4.5.50938
* Resharper 9.1.1
* DotCover 3.1.1
* Xunit Test Support for Resharper 9, v2.1.7

I will also clone this onto a dev machine at work - that has a Resharper 8.x I think.

**Comment by citizenmatt** [comment]
Nope, sorry, it works absolutely fine, whether I run it, debug it, add breakpoints, step through. Do you have any other extensions installed? OzCode perhaps?

**Comment by Pondidum** [comment]
The only other addon I have installed (other than all the Microsoft ones and Resharper) is Telerik JustDecompile.

I have also now tested on two other machines at work, both of which exhibit the problem too.

Machine 1:
Windows 7 x64, Visual Studio 2013 Update 4
Addons: Resharper 8.2.1, Telerik JustDecompile

Machine 2:
Windows 7 x64, Visual Studio 2013 Update 4
Addons: Resharper 8.2.1

And just to make sure, this is the line I have a breakpoint on:
https://github.com/Pondidum/XunitBug/blob/master/XunitBug/Tests.cs#L32
Stepping over that returns a random (?) number (different every run at least).
Stepping into works
Stepping into specific `XunitBug.IEventStore.GetLatestSequenceFor<TKey>` works

Interestingly, on the 2nd machine the debugger would not let me Step into the implementation, it only allowed me to step over or 'step into specific...'  Not sure if that is related or not.

**Comment by citizenmatt** [comment]
I really don't get how this could be happening. The call to `new` for `TestEventStore` should create an object with default values for the properties, which means `Value` should *always* be null. Neither ReSharper nor the xunit plugin have anything to do with debugging - we don't poke data into the debuggee's memory, so I really don't see how the default value for `Value` can be anything other than `null`.

Completely clutching at straws - do you have anything in the Watch windows that is perhaps setting the `store.Value` property?

**Comment by Pondidum** [comment]
Afraid not - nothing in any of the watch windows.
Inspecting the store object shows Value as being null, and calling the method manually in the Quick Watch window returns null too.

Changing the test to this also returns a random number when stepped over too:

    [Fact]
    public void When_faking_a_value()
    {
        var store = new TestEventStore();
        store.Value = 123;

        DoTest(store);
    }

    public void DoTest(IEventStore store)
    {
        var test = store.GetLatestSequenceFor(Guid.NewGuid());
        Assert.Equal(null, test);
    }

Very very strange indeed.

Moving the generic parameter definition from the method to the interface definition itself makes the whole thing work too...which is lucky as I need to do that anyway for my project, so hopefully won't hit this issue again.

Thanks for looking into it though.
Andy.

**Comment by citizenmatt** [comment]
OK, I'm going to have to leave this. I really can't figure out why it would be doing that, especially that last version, where you're explicitly setting the value, and it's still returning a random value. Last question - have you got RyuJIT installed? Perhaps there was a bug in the new jit?

**Comment by Pondidum** [comment]
Nope, nothing like that installed on any of the machines.

**Comment by citizenmatt** [comment]
Sorry, closing without repro. If you can repro on another machine, please reopen.
