### ISSUE TITLE
Tests not being detected

### ISSUE THREAD

**Issue by pmcgrath** [xunit/resharper-xunit#62]
I have added the ReSharper extension "xUnit.net Tests Support for ReSharper 9" v2.1.7 but it is not detecting any of my tests. 

My setup

### Environment
- VS: 2013 Update 4 (12.0.31101.0)
- ReSharper: 9.1.1
- ReSharper extension: "xUnit.net Tests Support for ReSharper 9" v2.1.7

### Solution\TestProject packages
```
  <package id="xunit" version="2.0.0" targetFramework="net45" />
  <package id="xunit.abstractions" version="2.0.0" targetFramework="net45" />
  <package id="xunit.assert" version="2.0.0" targetFramework="net45" />
  <package id="xunit.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.extensibility.core" version="2.0.0" targetFramework="net45" />
  <package id="xunit.runner.visualstudio" version="2.0.0" targetFramework="net45" />
```
I have added the "xunit.runner.visualstudio" package so I can run the tests via the VS Test Explorer window for now

If I look at the unit testing tools using ReSharper -> Options -> Tools -> Unit Testing
I can see the following are listed and can be configured to some degree
- NUnit
- MsTest
- JavaScript Tests

Should I not see an entry for xunit after the ReSharper extension installation ?

My tests look like 
```c#
    [Trait("UnitTests")]
    public class TestCase
    {
        [Fact]
        public void Test1()
        {
        }
    }
```
so there should be no issue with test discovery.

Thanks in advance
Pat

**Comment by citizenmatt** [comment]
No, there's nothing in the options for xunit - it just works (or doesn't). Have you restarted VS after installing? Is your ReSharper installation an all-users install, or just the normal per-user?

**Comment by pmcgrath** [comment]
Matt,
Did restart VS after installing
Have did the full install\uninstall restart cycle a number of times
My ReSharper installation is an all-users install I believe


Pat

**Comment by citizenmatt** [comment]
Ah, that's the issue. Annoyingly, all plugins are broken for an all-user install. The normal install is per-user, and all-user has been recently added, but unfortunately, completely broke plugins. Apparently, this is fixed in 9.2, and the EAP has just started. But the SDK for 9.2 isn't yet available, and so there are no plugins available for it just yet. It will be out by August, and the plugins will be updated, hopefully before that.

**Comment by pmcgrath** [comment]
Matt,
I presume this also applies to VS2015 ?

Thanks
Pat

**Comment by citizenmatt** [comment]
Yes, it's a resharper thing, not a Visual Studio thing.

**Comment by pmcgrath** [comment]
Do you know if its possible to switch from an "All Users" to "Current User" after a ReSharper installation ?

**Comment by citizenmatt** [comment]
I don't think you can "switch", but you can uninstall and reinstall.

**Comment by pmcgrath** [comment]
Matt 

FYI
I did an uninstall and reinstall as you suggested and can confirm that the tests are now detected.
I was using a trial version so I did not need to worry about a key, just ran the installer exe and indicated that I wanted to remove ReSharper. Ran installer again and accepted defaults which is to just install for the current user.

Thanks for our help
Pat

**Comment by citizenmatt** [comment]
No problem :thumbsup:

**Comment by marcelmunarolo** [comment]
Hello,
Same issue here, we have acquired some licenses for our company, and performed the installations with the "All User" options (since we are not Admins and the installation is performed by the Help Desk). 

I am looking forward to see how we could make it work.
Cheers!
Marcel
