### ISSUE TITLE
Add support for ReSharper 9.2 (EAP)

### ISSUE THREAD

**Issue by redoz** [xunit/resharper-xunit#63]
It would be nice if the new [EAP](https://confluence.jetbrains.com/display/ReSharper/ReSharper+9.2+EAP) was supported,

**Comment by citizenmatt** [comment]
It will be. The SDK isn't ready yet, though.

**Comment by drewnoakes** [comment]
+1 for this, especially now VS2015 RTM is out and R# 9.2 is more likely to be widely used.

**Comment by citizenmatt** [comment]
The SDK is out now, so expect it in the next couple of days.

**Comment by citizenmatt** [comment]
Hmm. Actually, it might have to be EAP4. It looks like EAP3 hasn't yet updated the default extension feed to look at 9.2 compatible packages.

**Comment by gotvino** [comment]
Any news on 9.2 EAP support?

**Comment by citizenmatt** [comment]
The 9.2 SDK is now available, so should be over the next couple of days.

**Comment by citizenmatt** [comment]
9.2 EAP 7 support just released. It's available via the Extension Manager. Make sure you enable pre-release extensions in ReSharper &rarr; Options &rarr; Extension Manager.
