### ISSUE TITLE
Resharper runner hangs when JSON.Net used in a test

### ISSUE THREAD

**Issue by mj1856** [xunit/resharper-xunit#64]
Extremely simple repo: https://gist.github.com/mj1856/0a21d5640f65ddcbf930

Running in VS2013 with Resharper 9, and xUnit for Resharper 2.0.7

When running the test in the ReSharper runner, it just hangs and never returns.  If I *debug* the test, it returns without hanging anywhere.

This doesn't occur in the VS runner.

I thought at first it might be related to the latest JSON.net release, but I tested on older versions with the same results.  Not sure what it is about this particular thing, but it hangs the runner.

**Comment by mj1856** [comment]
Ping @JamesNK also - thought I think it's on the xUnit-resharper side.  Any idea what it could be hung up on?  I tested Newtonsoft.Json 7.0.1 and 6.0.8.

**Comment by citizenmatt** [comment]
Just tried this with 2.1.7, and it doesn't hang - the test runs fine. I suspect the issue has been fixed. Try updating.

**Comment by mj1856** [comment]
Ok, I upgraded from 9.0u1 to 9.1, then got xUnit 2.1.7.  Still hung.

Then tried switching from auto to x64 - still hung.  Switch to x86 and works.

Stumped, so did a full reboot (which I should have done sooner).  Now works in all modes.

Not sure what it was exactly, but something in x64 mode only got cleared with a full reboot.

Reminds me of this xkcd:

![image](https://cloud.githubusercontent.com/assets/1396388/8513349/485b4af0-231c-11e5-8104-b23fd72eef4a.png)

Thanks, and sorry!

**Comment by citizenmatt** [comment]
Computers. More trouble than they're worth :) At least it's working!
