### ISSUE TITLE
Theory with custom attribute having internal access modifier causes downstream tests not to run

### ISSUE THREAD

**Issue by eroller** [xunit/resharper-xunit#66]
![image](https://cloud.githubusercontent.com/assets/2440289/8579383/1d59a956-2569-11e5-917c-75394a57bf4a.png)

related to http://stackoverflow.com/questions/31279955/test-missing-when-using-autofixture-with-nsubstitute-auto-data-attribute

**Comment by eroller** [comment]
similar to https://github.com/xunit/resharper-xunit/issues/65

**Comment by eroller** [comment]
switching internal to public allows all the tests to run. However, the behavior in https://github.com/xunit/resharper-xunit/issues/65 is still observed.

**Comment by citizenmatt** [comment]
This appears to be an xunit issue - it happens with the Visual Studio runner, too. And it's about the constructor - if the constructor is internal, those tests are ignored. If it's public, it runs. @bradwilson?

**Comment by eroller** [comment]
yes, and with TestDriven.Net runner the tests actually fail, instead of just not being discovered.

**Comment by bradwilson** [comment]
@eroller Please open a separate issue with https://github.com/xunit/xunit/issues. Thanks.

**Comment by eroller** [comment]
moved to https://github.com/xunit/xunit/issues/465
