### ISSUE TITLE
Test Output is duplicated while running

### ISSUE THREAD

**Issue by tdupont750** [xunit/resharper-xunit#70]
Output in the test output pane is duplicated while running, but then corrects itself when the test completes.

**While running:**

48.337 Hello
48.337 Hello
49.361 World
48.337 Hello
49.361 World
50.374 Goodnight
48.337 Hello
49.361 World
50.374 Goodnight
51.388 Moon

**When complete:**

48.337 Hello
49.361 World
50.374 Goodnight
51.388 Moon

**Sample Test**

public class TestClass
{
  private readonly ITestOutputHelper _testOutputHelper;

  public TestClass(ITestOutputHelper testOutputHelper)
  {
    _testOutputHelper = testOutputHelper;
  }

  [Fact]
  public async Task WriteLine()
  {
    _testOutputHelper.WriteLine(DateTime.Now.ToString("ss.fff") + " Hello");
    await Task.Delay(1000);
    _testOutputHelper.WriteLine(DateTime.Now.ToString("ss.fff") + " World");
    await Task.Delay(1000);
    _testOutputHelper.WriteLine(DateTime.Now.ToString("ss.fff") + " Goodnight");
    await Task.Delay(1000);
    _testOutputHelper.WriteLine(DateTime.Now.ToString("ss.fff") + " Moon");
    await Task.Delay(5000);
  }
}

**Comment by citizenmatt** [comment]
I can't recreate this. What are the versions of xunit and the plugin? I've tested with 2.0.0 and 2.1.7, respectively. And ReSharper 9.1.1.

**Comment by tdupont750** [comment]
Sorry, I always forget the simple things:
* Visual Studio Professional 2013
* ReSharper 8.2 C# Edition build 8.2.0.2160
* xunitcontrib 2.1.7

Maybe it is time for me to upgrade to ReSharper 9...

**Comment by citizenmatt** [comment]
It might be this bug - [RSRP-411171](https://youtrack.jetbrains.com/issue/RSRP-411171), which looks like it's been fixed in a later version of 8.2. Try downloading 8.2.3 from the [download archives](http://resharper-support.jetbrains.com/hc/en-us/articles/206104048-Where-can-I-download-an-old-previous-ReSharper-version-), and see how that works.

**Comment by tdupont750** [comment]
That fixed it, thank you very much!
