### ISSUE TITLE
xUnit.net Test Support 2.1.7 reports incorrect runtimes for xunit 2.0.0

### ISSUE THREAD

**Issue by ben-biddington** [xunit/resharper-xunit#73]
Hi, 

I have `xUnit.net Test Support 2.1.7` installed in VS 2013 and when I run my tests in resharper a `55s` test run is reported as `5.37.250`.

I have full parallel mode on -- no `xunit.` appsettings defined.

Am I missing something?

**Comment by ben-biddington** [comment]
JetBrains ReSharper 8.2 C# Edition
Build 8.2.0.2160 on 2014-03-20T07:53:08

Plugins: 3
#1. Untitled v1.3.0.0 by Anonymous
#2. “NuGet support for ReSharper” v1.3.0.35071 by JetBrains
#3. “xUnit.net unit test provider” v2.0.6.25611 by “Matt Ellis”
Visual Studio 12.0.30723.0.

Copyright © 2003–2015 JetBrains s.r.o. All rights reserved.

**Comment by ben-biddington** [comment]
Hmm, that tells me a different version

**Comment by ben-biddington** [comment]
![xuit-contrib](https://cloud.githubusercontent.com/assets/32415/9368107/8f55acda-4715-11e5-8080-80a33e12d090.PNG)

**Comment by ben-biddington** [comment]
Will try {un,re}install

**Comment by citizenmatt** [comment]
Is this still an issue? Please reopen if so.
