### ISSUE TITLE
xUnit and vNext is found but not executed/run

### ISSUE THREAD

**Issue by danielwertheim** [xunit/resharper-xunit#75]
If you follow e.g. this http://xunit.github.io/docs/getting-started-dnx.html the runner in ReSharper finds the tests, but does not execute them. Result is: `Inconclusive: Test not run`

ReSharper 9.2

**Comment by mojodomo** [comment]
I am having the same exact issue.  Any updates on this?

**Comment by jtdunlop** [comment]
It looks for a DLL at artifacts\bin\\{project}\\{project}.dll, but it resides in {project}\bin\debug\\{framework}

**Comment by jtdunlop** [comment]
dnx . test (beta5) does work from the test project folder.

**Comment by VZhuck** [comment]
Issue still exists
I believe fix is simple: just update TestEnvironment class and take in account "{framework}"

Does it make sense to make Assembly path template configurable?

**Comment by Aerendel** [comment]
Any update on this issue? This completely blocks us from user the Resharper runner and NCover on .Net vNext

**Comment by citizenmatt** [comment]
Sorry, this requires a change in ReSharper. It was originally going to happen in 10.0, but it's not made it. Next release hopefully. And it shouldn't stop you using ncover - that's not a resharper thing.

**Comment by Aerendel** [comment]
Thanks for the update. Also, I meant dotCover not NCover - I blame fast typing.

**Comment by rick-sanchez** [comment]
I get this on resharper 10.0.0.2 xUnit.net Test Support 2.3.2, specifically: "Unit Test Runner failed to run tests" "Unable to run xUnit.net tests - File not found: (projectDir)\artifacts\bin\(project)\(project).dll . If I enable project properties -> build -> produce outputs on build, then dll gets wrote to (path can change per build/framework settings) (projectDir)\artifacts\bin\(project)\Debug\dnxcore50. If I change the "run tests from" option in resharper to this folder it instead gives me an error about not able to find xunit.dll.

**Comment by rick-sanchez** [comment]
This issue probably just needs to be merged into https://github.com/xunit/resharper-xunit/issues/38

**Comment by citizenmatt** [comment]
Closing in favour of #38
