### ISSUE TITLE
Running single tests that are in an ignored category is not possible anymore

### ISSUE THREAD

**Issue by thedmi** [xunit/resharper-xunit#76]
This is a regression. I have this problem since I've updated to R# 9.2 and resharper-xunit 2.2.8. 

When running tests explicitly (e.g. by using the action icon next to a test method), the test should be run regardless of any ignore settings.  Since the update, they are ignored, however.

**Comment by citizenmatt** [comment]
Can you remember when it last worked? I've just tried 9.2 + 9.1, and both will treat this test as ignored.

**Comment by thedmi** [comment]
I think I was running R# 9.1.2 when it last worked, but I don't remember the version of the xunit extension. If I remember incorrectly, then it was R# 9.0 and not lower, that's for sure.

**Comment by citizenmatt** [comment]
Thanks. I'm confused by this one - I don't know how it's ever worked :)

@bradwilson is there anything in the API that would allow a runner to force a skipped test to run?

**Comment by thedmi** [comment]
I see :-) 

Here is some more background information: At the beginning of the project, I tried to get the "run only when explicitly started" behavior by just adding `Skip` to the `[Fact]`. That didn't work, the test was never run, even when started directly. I then found that I could ignore whole categories (e.g. `[Trait("Category", "NoAutoRun")]` ) by specifying the category name in the Resharper options under *Tools > Unit Testing > Skip tests from categories*. With this approach, the test *was* run when started directly, but skipped when running a bunch of them, e.g. with *Run test in solution*.

So that was the path we took, but it stopped working with the update to R# 9.2.

**Comment by thedmi** [comment]
And by the way, we've been using xunit.net 1.9.2 since quite some time and haven't changed anything on that end.

**Comment by citizenmatt** [comment]
Aha! I can recreate that. And sadly, it's a regression in ReSharper, and affects nunit, too. Here's the ticket: [RSRP-447562](https://youtrack.jetbrains.com/issue/RSRP-447652) for you to track and vote. I'm going to close this issue, as there's not much I can do here.
