### ISSUE TITLE
Executing tests that are not selected

### ISSUE THREAD

**Issue by danielwertheim** [xunit/resharper-xunit#77]
When selecting a "group/folder" with tests in the ReSharper Unit test explorer to be executed, it kicks of tests in other "groups/folders" as well.

E.g. as seen in the attachments. I selected "UnitTests" it also adds "IntegrationTests" to the test session and runs them.

![xunit-resharper-unittestexplorer](https://cloud.githubusercontent.com/assets/196044/9698286/7b1d3a0c-53af-11e5-845a-5d2843ea13da.PNG)

![xunit-resharper-unittestsessions](https://cloud.githubusercontent.com/assets/196044/9698287/7ff558a2-53af-11e5-8185-f2a3b81927d9.PNG)

**Comment by citizenmatt** [comment]
I'm afraid this is a bug in ReSharper 9.2, and nothing I can do to fix it in the runner. It happens for nunit too. You can track and vote on the issue here: [RSRP-442501](https://youtrack.jetbrains.com/issue/RSRP-442501).

**Comment by danielwertheim** [comment]
Got it. Will vote.
