### ISSUE TITLE
ReSharper 10 EAP support

### ISSUE THREAD

**Issue by sevenate** [xunit/resharper-xunit#82]
As this awesome extension is not available from ReSharper's extension manager I assume that version 10 is not yet officially supported, is that correct?

If so, are there any hope/plans/ETA when xUnit test runner will be back available for latest ReSharper?

**Comment by DoCode** [comment]
+1
(?)

**Comment by jeremy-holt** [comment]
It would be great if you could notify us through the jetbrains blog when a compatible version has been released for the current EAP. Much as I would like to test the EAP, I can't use it without the XUnit test runner.

**Comment by DoCode** [comment]
When can we perform tests again, with NUnit and ReSharper EAP8?

**Comment by luisrudge** [comment]
:+1: I'm using the EAP but it doesn't find my xunit tests

**Comment by rstaib** [comment]
+1

**Comment by reijerh** [comment]
Yes please.

**Comment by citizenmatt** [comment]
It's coming! Working on it right now.

**Comment by joplaal** [comment]
Does it will solve also https://github.com/xunit/resharper-xunit/issues/58 ? (DNX support) 
Does Resharper 10 bring DNX Test runner support?

**Comment by citizenmatt** [comment]
No, it won't. That requires an update from ReSharper itself. We were hoping to get that into 10.0, but it didn't happen.

**Comment by ErikSchierboom** [comment]
@citizenmatt Great! Looking forward to it.

**Comment by luizbon** [comment]
@citizenmatt do you need any help with that? I can do tests if you want or even help on coding...

**Comment by citizenmatt** [comment]
@luizbon thanks! Just about had things done when you commented, so didn't take you up on this, but really appreciate the offer.
