### ISSUE TITLE
Resharper 7.1 support?

### ISSUE THREAD

**Issue by csaket** [xunit/resharper-xunit#83]
Hi

I have Resharper 7.1 which I use with VS 2012.
I am not able to use the new xunit 2.1.0 with Resharper as the xunit plugin is expecting xunit.dll which is no longer present in the new xunit 2.1.0 

Can someone guide me on what plugin supports both Resharper 7.1 and xunit 2.1.0

Thanks

**Comment by citizenmatt** [comment]
Sorry, there isn't a version of the plugin for 7.1 that runs xunit 2. The first version that supported xunit 2 was for 8.2.
