### ISSUE TITLE
CodeLens does not show tests as passing

### ISSUE THREAD

**Issue by papadi** [xunit/resharper-xunit#84]
CodeLens does not display tests as passing when they are executed with resharper-xunit. CodeLense does work though if the same xunit tests are executed using the out of the box runner.

![image](https://cloud.githubusercontent.com/assets/3359377/10863674/45d7e902-7fd6-11e5-88ad-13c8b2b01b9d.png)

**Comment by citizenmatt** [comment]
Unfortunately, the CodeLens indicators can only be updated by the Visual Studio runner. The ReSharper runner can't update them at all. If you want to use these indicators, you'll have to use the VS runner.

**Comment by PureKrome** [comment]
@citizenmatt I know this issue is closed - but why can't the R# runner access code lens, yet the VS runner can?

**Comment by bradwilson** [comment]
There is a hard-coded tie between the VS runner and Code Lens; that's why.

**Comment by PureKrome** [comment]
@bradwilson do you mean, a hardcoded ONE WAY LINK _from_ CodeLens down into VS Runner .. not the other way around (via a code lens public api) ?

**Comment by bradwilson** [comment]
As far as I know, CodeLens is hard-coded to look into the VS test runner.

https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/5743423-provide-an-open-api-to-allow-us-to-extend-code-len

**Comment by PureKrome** [comment]
Ta mate!
