### ISSUE TITLE
resharper plugin no longer available after upgrade from R# 9.2 to R# 10

### ISSUE THREAD

**Issue by robbiekouwenberg** [xunit/resharper-xunit#92]
Hi,

After upgrading to R# 10, i was no longer able to discover and run unit tests.
At first i thought the plugin had stopped working but after searching i found that the plugin was no longer installed.
I tried reinstalling through the R# extensions manager but the plugin cannot be found there, i even checked with prerelease packages enabled.
Is this a known issue?

Greetings,
Robbie

**Comment by citizenmatt** [comment]
Hi. I'm updating it now, should be available by the end of the day. Closing this in favour of #82.

**Comment by robbiekouwenberg** [comment]
Nice!
Keep up the good work!

-----Original Message-----
