### ISSUE TITLE
Resharper 10 RTW

### ISSUE THREAD

**Issue by DoCode** [xunit/resharper-xunit#94]
Hi Matt,
whats going on w/ r#10.rtw support?
Greetings...

**Comment by citizenmatt** [comment]
Hi. Busy cherry picking right now :)

It's all done, just need to rearrange some code to also get a bug fix out for 9.2.

I'm going to close this in favour of #82...

**Comment by DoCode** [comment]
Nice. I'm in a curious situation. I'm updated to vs2015.u1.rc and the r# 10.eap bits... And for over a week i can not testing... :smile:
