### ISSUE TITLE
Resharper 10

### ISSUE THREAD

**Issue by jeremy-holt** [xunit/resharper-xunit#95]
Just installed the latest version into R# 10 RTM and no output appears in the output window.

**Comment by citizenmatt** [comment]
Sadly, this is a [bug in ReSharper](https://youtrack.jetbrains.com/issue/RSRP-450266). It's already been fixed, and a hot fix will be available in the next few days, likely sometime next week. There's a workaround in [the release notes](https://github.com/xunit/resharper-xunit/releases/tag/release-2.3.0).
