### ISSUE TITLE
v 2.3.0 does not discover tests?

### ISSUE THREAD

**Issue by bdaniel7** [xunit/resharper-xunit#97]
I'm running VS 2013, Resharper 10 RTM with xUnit 2.1.0 and resharper-xunit 2.3.0.

Although I have tests marked with [Fact], VS (or R#) doesn't show the green bullet so that I can run the tests.
Nor do they appear in the Unit Test Explorer.
And in the Resharper Unit Testing settings there is no xUnit category, like for nUnit or MsTest.

Any idea if this is a Resharper bug or an extension bug?

**Comment by citizenmatt** [comment]
Did you restart after installing?

**Comment by bdaniel7** [comment]
Restarted VS. Should I have restarted the machine as well?

**Comment by citizenmatt** [comment]
Nope, just VS. Have you installed ReSharper as a per-machine installation? Extensions aren't supported in this scenario, and you have to install per-user.

**Comment by bdaniel7** [comment]
I'm not sure. I'll check Monday.

**Comment by bdaniel7** [comment]
I checked my home dev machine and the tests are discovered and I can run them. So very likely the problem is the way I installed Resharper on my work dev machine. Thanks for the help!

**Comment by bdaniel7** [comment]
So the problem was the per-machine installation mode. I repaired Resharper and now I can run the tests.
